/*
 * This source file was generated by FireStorm/DAO.
 * 
 * If you purchase a full license for FireStorm/DAO you can customize this header file.
 * 
 * For more information please visit http://www.codefutures.com/products/firestorm
 */

package edu.co.sena.onlineshop.integracion.dto;

import edu.co.sena.onlineshop.integracion.dao.*;
import edu.co.sena.onlineshop.integracion.factory.*;
import edu.co.sena.onlineshop.integracion.exceptions.*;
import java.io.Serializable;
import java.util.*;

public class InventarioCompras implements Serializable
{
	/** 
	 * This attribute maps to the column ID_INVENTARIO in the inventario_compras table.
	 */
	protected int idInventario;

	/** 
	 * This attribute represents whether the attribute idInventario has been modified since being read from the database.
	 */
	protected boolean idInventarioModified = false;

	/** 
	 * This attribute maps to the column PRODUCTO_ID_PRODUCTO in the inventario_compras table.
	 */
	protected String productoIdProducto;

	/** 
	 * This attribute represents whether the attribute productoIdProducto has been modified since being read from the database.
	 */
	protected boolean productoIdProductoModified = false;

	/** 
	 * This attribute maps to the column CAN_PRO_COMPRADO in the inventario_compras table.
	 */
	protected int canProComprado;

	/** 
	 * This attribute represents whether the primitive attribute canProComprado is null.
	 */
	protected boolean canProCompradoNull = true;

	/** 
	 * This attribute represents whether the attribute canProComprado has been modified since being read from the database.
	 */
	protected boolean canProCompradoModified = false;

	/** 
	 * This attribute maps to the column FECHA_COMPRA in the inventario_compras table.
	 */
	protected String fechaCompra;

	/** 
	 * This attribute represents whether the attribute fechaCompra has been modified since being read from the database.
	 */
	protected boolean fechaCompraModified = false;

	/** 
	 * This attribute maps to the column PROVEEDOR_TIPO_DOCUMENTO in the inventario_compras table.
	 */
	protected String proveedorTipoDocumento;

	/** 
	 * This attribute represents whether the attribute proveedorTipoDocumento has been modified since being read from the database.
	 */
	protected boolean proveedorTipoDocumentoModified = false;

	/** 
	 * This attribute maps to the column PROVEEDOR_NUM_DOCUMENTO in the inventario_compras table.
	 */
	protected String proveedorNumDocumento;

	/** 
	 * This attribute represents whether the attribute proveedorNumDocumento has been modified since being read from the database.
	 */
	protected boolean proveedorNumDocumentoModified = false;

	/**
	 * Method 'InventarioCompras'
	 * 
	 */
	public InventarioCompras()
	{
	}

	/**
	 * Method 'getIdInventario'
	 * 
	 * @return int
	 */
	public int getIdInventario()
	{
		return idInventario;
	}

	/**
	 * Method 'setIdInventario'
	 * 
	 * @param idInventario
	 */
	public void setIdInventario(int idInventario)
	{
		this.idInventario = idInventario;
		this.idInventarioModified = true;
	}

	/** 
	 * Sets the value of idInventarioModified
	 */
	public void setIdInventarioModified(boolean idInventarioModified)
	{
		this.idInventarioModified = idInventarioModified;
	}

	/** 
	 * Gets the value of idInventarioModified
	 */
	public boolean isIdInventarioModified()
	{
		return idInventarioModified;
	}

	/**
	 * Method 'getProductoIdProducto'
	 * 
	 * @return String
	 */
	public String getProductoIdProducto()
	{
		return productoIdProducto;
	}

	/**
	 * Method 'setProductoIdProducto'
	 * 
	 * @param productoIdProducto
	 */
	public void setProductoIdProducto(String productoIdProducto)
	{
		this.productoIdProducto = productoIdProducto;
		this.productoIdProductoModified = true;
	}

	/** 
	 * Sets the value of productoIdProductoModified
	 */
	public void setProductoIdProductoModified(boolean productoIdProductoModified)
	{
		this.productoIdProductoModified = productoIdProductoModified;
	}

	/** 
	 * Gets the value of productoIdProductoModified
	 */
	public boolean isProductoIdProductoModified()
	{
		return productoIdProductoModified;
	}

	/**
	 * Method 'getCanProComprado'
	 * 
	 * @return int
	 */
	public int getCanProComprado()
	{
		return canProComprado;
	}

	/**
	 * Method 'setCanProComprado'
	 * 
	 * @param canProComprado
	 */
	public void setCanProComprado(int canProComprado)
	{
		this.canProComprado = canProComprado;
		this.canProCompradoNull = false;
		this.canProCompradoModified = true;
	}

	/**
	 * Method 'setCanProCompradoNull'
	 * 
	 * @param value
	 */
	public void setCanProCompradoNull(boolean value)
	{
		this.canProCompradoNull = value;
		this.canProCompradoModified = true;
	}

	/**
	 * Method 'isCanProCompradoNull'
	 * 
	 * @return boolean
	 */
	public boolean isCanProCompradoNull()
	{
		return canProCompradoNull;
	}

	/** 
	 * Sets the value of canProCompradoModified
	 */
	public void setCanProCompradoModified(boolean canProCompradoModified)
	{
		this.canProCompradoModified = canProCompradoModified;
	}

	/** 
	 * Gets the value of canProCompradoModified
	 */
	public boolean isCanProCompradoModified()
	{
		return canProCompradoModified;
	}

	/**
	 * Method 'getFechaCompra'
	 * 
	 * @return String
	 */
	public String getFechaCompra()
	{
		return fechaCompra;
	}

	/**
	 * Method 'setFechaCompra'
	 * 
	 * @param fechaCompra
	 */
	public void setFechaCompra(String fechaCompra)
	{
		this.fechaCompra = fechaCompra;
		this.fechaCompraModified = true;
	}

	/** 
	 * Sets the value of fechaCompraModified
	 */
	public void setFechaCompraModified(boolean fechaCompraModified)
	{
		this.fechaCompraModified = fechaCompraModified;
	}

	/** 
	 * Gets the value of fechaCompraModified
	 */
	public boolean isFechaCompraModified()
	{
		return fechaCompraModified;
	}

	/**
	 * Method 'getProveedorTipoDocumento'
	 * 
	 * @return String
	 */
	public String getProveedorTipoDocumento()
	{
		return proveedorTipoDocumento;
	}

	/**
	 * Method 'setProveedorTipoDocumento'
	 * 
	 * @param proveedorTipoDocumento
	 */
	public void setProveedorTipoDocumento(String proveedorTipoDocumento)
	{
		this.proveedorTipoDocumento = proveedorTipoDocumento;
		this.proveedorTipoDocumentoModified = true;
	}

	/** 
	 * Sets the value of proveedorTipoDocumentoModified
	 */
	public void setProveedorTipoDocumentoModified(boolean proveedorTipoDocumentoModified)
	{
		this.proveedorTipoDocumentoModified = proveedorTipoDocumentoModified;
	}

	/** 
	 * Gets the value of proveedorTipoDocumentoModified
	 */
	public boolean isProveedorTipoDocumentoModified()
	{
		return proveedorTipoDocumentoModified;
	}

	/**
	 * Method 'getProveedorNumDocumento'
	 * 
	 * @return String
	 */
	public String getProveedorNumDocumento()
	{
		return proveedorNumDocumento;
	}

	/**
	 * Method 'setProveedorNumDocumento'
	 * 
	 * @param proveedorNumDocumento
	 */
	public void setProveedorNumDocumento(String proveedorNumDocumento)
	{
		this.proveedorNumDocumento = proveedorNumDocumento;
		this.proveedorNumDocumentoModified = true;
	}

	/** 
	 * Sets the value of proveedorNumDocumentoModified
	 */
	public void setProveedorNumDocumentoModified(boolean proveedorNumDocumentoModified)
	{
		this.proveedorNumDocumentoModified = proveedorNumDocumentoModified;
	}

	/** 
	 * Gets the value of proveedorNumDocumentoModified
	 */
	public boolean isProveedorNumDocumentoModified()
	{
		return proveedorNumDocumentoModified;
	}

	/**
	 * Method 'equals'
	 * 
	 * @param _other
	 * @return boolean
	 */
	public boolean equals(Object _other)
	{
		if (_other == null) {
			return false;
		}
		
		if (_other == this) {
			return true;
		}
		
		if (!(_other instanceof InventarioCompras)) {
			return false;
		}
		
		final InventarioCompras _cast = (InventarioCompras) _other;
		if (idInventario != _cast.idInventario) {
			return false;
		}
		
		if (idInventarioModified != _cast.idInventarioModified) {
			return false;
		}
		
		if (productoIdProducto == null ? _cast.productoIdProducto != productoIdProducto : !productoIdProducto.equals( _cast.productoIdProducto )) {
			return false;
		}
		
		if (productoIdProductoModified != _cast.productoIdProductoModified) {
			return false;
		}
		
		if (canProComprado != _cast.canProComprado) {
			return false;
		}
		
		if (canProCompradoNull != _cast.canProCompradoNull) {
			return false;
		}
		
		if (canProCompradoModified != _cast.canProCompradoModified) {
			return false;
		}
		
		if (fechaCompra == null ? _cast.fechaCompra != fechaCompra : !fechaCompra.equals( _cast.fechaCompra )) {
			return false;
		}
		
		if (fechaCompraModified != _cast.fechaCompraModified) {
			return false;
		}
		
		if (proveedorTipoDocumento == null ? _cast.proveedorTipoDocumento != proveedorTipoDocumento : !proveedorTipoDocumento.equals( _cast.proveedorTipoDocumento )) {
			return false;
		}
		
		if (proveedorTipoDocumentoModified != _cast.proveedorTipoDocumentoModified) {
			return false;
		}
		
		if (proveedorNumDocumento == null ? _cast.proveedorNumDocumento != proveedorNumDocumento : !proveedorNumDocumento.equals( _cast.proveedorNumDocumento )) {
			return false;
		}
		
		if (proveedorNumDocumentoModified != _cast.proveedorNumDocumentoModified) {
			return false;
		}
		
		return true;
	}

	/**
	 * Method 'hashCode'
	 * 
	 * @return int
	 */
	public int hashCode()
	{
		int _hashCode = 0;
		_hashCode = 29 * _hashCode + idInventario;
		_hashCode = 29 * _hashCode + (idInventarioModified ? 1 : 0);
		if (productoIdProducto != null) {
			_hashCode = 29 * _hashCode + productoIdProducto.hashCode();
		}
		
		_hashCode = 29 * _hashCode + (productoIdProductoModified ? 1 : 0);
		_hashCode = 29 * _hashCode + canProComprado;
		_hashCode = 29 * _hashCode + (canProCompradoNull ? 1 : 0);
		_hashCode = 29 * _hashCode + (canProCompradoModified ? 1 : 0);
		if (fechaCompra != null) {
			_hashCode = 29 * _hashCode + fechaCompra.hashCode();
		}
		
		_hashCode = 29 * _hashCode + (fechaCompraModified ? 1 : 0);
		if (proveedorTipoDocumento != null) {
			_hashCode = 29 * _hashCode + proveedorTipoDocumento.hashCode();
		}
		
		_hashCode = 29 * _hashCode + (proveedorTipoDocumentoModified ? 1 : 0);
		if (proveedorNumDocumento != null) {
			_hashCode = 29 * _hashCode + proveedorNumDocumento.hashCode();
		}
		
		_hashCode = 29 * _hashCode + (proveedorNumDocumentoModified ? 1 : 0);
		return _hashCode;
	}

	/**
	 * Method 'createPk'
	 * 
	 * @return InventarioComprasPk
	 */
	public InventarioComprasPk createPk()
	{
		return new InventarioComprasPk(idInventario, productoIdProducto, proveedorTipoDocumento, proveedorNumDocumento);
	}

	/**
	 * Method 'toString'
	 * 
	 * @return String
	 */
	public String toString()
	{
		StringBuffer ret = new StringBuffer();
		ret.append( "edu.co.sena.onlineshop.integracion.dto.InventarioCompras: " );
		ret.append( "idInventario=" + idInventario );
		ret.append( ", productoIdProducto=" + productoIdProducto );
		ret.append( ", canProComprado=" + canProComprado );
		ret.append( ", fechaCompra=" + fechaCompra );
		ret.append( ", proveedorTipoDocumento=" + proveedorTipoDocumento );
		ret.append( ", proveedorNumDocumento=" + proveedorNumDocumento );
		return ret.toString();
	}

}
