/*
 * This source file was generated by FireStorm/DAO.
 * 
 * If you purchase a full license for FireStorm/DAO you can customize this header file.
 * 
 * For more information please visit http://www.codefutures.com/products/firestorm
 */

package edu.co.sena.onlineshop.integracion.dto;

import edu.co.sena.onlineshop.integracion.dao.*;
import edu.co.sena.onlineshop.integracion.factory.*;
import edu.co.sena.onlineshop.integracion.exceptions.*;
import java.io.Serializable;
import java.util.*;

public class Item implements Serializable
{
	/** 
	 * This attribute maps to the column PRODUCTO_ID_PRODUCTO in the item table.
	 */
	protected String productoIdProducto;

	/** 
	 * This attribute represents whether the attribute productoIdProducto has been modified since being read from the database.
	 */
	protected boolean productoIdProductoModified = false;

	/** 
	 * This attribute maps to the column CANTIDAD in the item table.
	 */
	protected int cantidad;

	/** 
	 * This attribute represents whether the primitive attribute cantidad is null.
	 */
	protected boolean cantidadNull = true;

	/** 
	 * This attribute represents whether the attribute cantidad has been modified since being read from the database.
	 */
	protected boolean cantidadModified = false;

	/** 
	 * This attribute maps to the column COSTO_UNITARIO in the item table.
	 */
	protected String costoUnitario;

	/** 
	 * This attribute represents whether the attribute costoUnitario has been modified since being read from the database.
	 */
	protected boolean costoUnitarioModified = false;

	/** 
	 * This attribute maps to the column COSTO_TOTAL in the item table.
	 */
	protected String costoTotal;

	/** 
	 * This attribute represents whether the attribute costoTotal has been modified since being read from the database.
	 */
	protected boolean costoTotalModified = false;

	/** 
	 * This attribute maps to the column PEDIDO_FACTURA_ID_FACTURA in the item table.
	 */
	protected int pedidoFacturaIdFactura;

	/** 
	 * This attribute represents whether the attribute pedidoFacturaIdFactura has been modified since being read from the database.
	 */
	protected boolean pedidoFacturaIdFacturaModified = false;

	/**
	 * Method 'Item'
	 * 
	 */
	public Item()
	{
	}

	/**
	 * Method 'getProductoIdProducto'
	 * 
	 * @return String
	 */
	public String getProductoIdProducto()
	{
		return productoIdProducto;
	}

	/**
	 * Method 'setProductoIdProducto'
	 * 
	 * @param productoIdProducto
	 */
	public void setProductoIdProducto(String productoIdProducto)
	{
		this.productoIdProducto = productoIdProducto;
		this.productoIdProductoModified = true;
	}

	/** 
	 * Sets the value of productoIdProductoModified
	 */
	public void setProductoIdProductoModified(boolean productoIdProductoModified)
	{
		this.productoIdProductoModified = productoIdProductoModified;
	}

	/** 
	 * Gets the value of productoIdProductoModified
	 */
	public boolean isProductoIdProductoModified()
	{
		return productoIdProductoModified;
	}

	/**
	 * Method 'getCantidad'
	 * 
	 * @return int
	 */
	public int getCantidad()
	{
		return cantidad;
	}

	/**
	 * Method 'setCantidad'
	 * 
	 * @param cantidad
	 */
	public void setCantidad(int cantidad)
	{
		this.cantidad = cantidad;
		this.cantidadNull = false;
		this.cantidadModified = true;
	}

	/**
	 * Method 'setCantidadNull'
	 * 
	 * @param value
	 */
	public void setCantidadNull(boolean value)
	{
		this.cantidadNull = value;
		this.cantidadModified = true;
	}

	/**
	 * Method 'isCantidadNull'
	 * 
	 * @return boolean
	 */
	public boolean isCantidadNull()
	{
		return cantidadNull;
	}

	/** 
	 * Sets the value of cantidadModified
	 */
	public void setCantidadModified(boolean cantidadModified)
	{
		this.cantidadModified = cantidadModified;
	}

	/** 
	 * Gets the value of cantidadModified
	 */
	public boolean isCantidadModified()
	{
		return cantidadModified;
	}

	/**
	 * Method 'getCostoUnitario'
	 * 
	 * @return String
	 */
	public String getCostoUnitario()
	{
		return costoUnitario;
	}

	/**
	 * Method 'setCostoUnitario'
	 * 
	 * @param costoUnitario
	 */
	public void setCostoUnitario(String costoUnitario)
	{
		this.costoUnitario = costoUnitario;
		this.costoUnitarioModified = true;
	}

	/** 
	 * Sets the value of costoUnitarioModified
	 */
	public void setCostoUnitarioModified(boolean costoUnitarioModified)
	{
		this.costoUnitarioModified = costoUnitarioModified;
	}

	/** 
	 * Gets the value of costoUnitarioModified
	 */
	public boolean isCostoUnitarioModified()
	{
		return costoUnitarioModified;
	}

	/**
	 * Method 'getCostoTotal'
	 * 
	 * @return String
	 */
	public String getCostoTotal()
	{
		return costoTotal;
	}

	/**
	 * Method 'setCostoTotal'
	 * 
	 * @param costoTotal
	 */
	public void setCostoTotal(String costoTotal)
	{
		this.costoTotal = costoTotal;
		this.costoTotalModified = true;
	}

	/** 
	 * Sets the value of costoTotalModified
	 */
	public void setCostoTotalModified(boolean costoTotalModified)
	{
		this.costoTotalModified = costoTotalModified;
	}

	/** 
	 * Gets the value of costoTotalModified
	 */
	public boolean isCostoTotalModified()
	{
		return costoTotalModified;
	}

	/**
	 * Method 'getPedidoFacturaIdFactura'
	 * 
	 * @return int
	 */
	public int getPedidoFacturaIdFactura()
	{
		return pedidoFacturaIdFactura;
	}

	/**
	 * Method 'setPedidoFacturaIdFactura'
	 * 
	 * @param pedidoFacturaIdFactura
	 */
	public void setPedidoFacturaIdFactura(int pedidoFacturaIdFactura)
	{
		this.pedidoFacturaIdFactura = pedidoFacturaIdFactura;
		this.pedidoFacturaIdFacturaModified = true;
	}

	/** 
	 * Sets the value of pedidoFacturaIdFacturaModified
	 */
	public void setPedidoFacturaIdFacturaModified(boolean pedidoFacturaIdFacturaModified)
	{
		this.pedidoFacturaIdFacturaModified = pedidoFacturaIdFacturaModified;
	}

	/** 
	 * Gets the value of pedidoFacturaIdFacturaModified
	 */
	public boolean isPedidoFacturaIdFacturaModified()
	{
		return pedidoFacturaIdFacturaModified;
	}

	/**
	 * Method 'equals'
	 * 
	 * @param _other
	 * @return boolean
	 */
	public boolean equals(Object _other)
	{
		if (_other == null) {
			return false;
		}
		
		if (_other == this) {
			return true;
		}
		
		if (!(_other instanceof Item)) {
			return false;
		}
		
		final Item _cast = (Item) _other;
		if (productoIdProducto == null ? _cast.productoIdProducto != productoIdProducto : !productoIdProducto.equals( _cast.productoIdProducto )) {
			return false;
		}
		
		if (productoIdProductoModified != _cast.productoIdProductoModified) {
			return false;
		}
		
		if (cantidad != _cast.cantidad) {
			return false;
		}
		
		if (cantidadNull != _cast.cantidadNull) {
			return false;
		}
		
		if (cantidadModified != _cast.cantidadModified) {
			return false;
		}
		
		if (costoUnitario == null ? _cast.costoUnitario != costoUnitario : !costoUnitario.equals( _cast.costoUnitario )) {
			return false;
		}
		
		if (costoUnitarioModified != _cast.costoUnitarioModified) {
			return false;
		}
		
		if (costoTotal == null ? _cast.costoTotal != costoTotal : !costoTotal.equals( _cast.costoTotal )) {
			return false;
		}
		
		if (costoTotalModified != _cast.costoTotalModified) {
			return false;
		}
		
		if (pedidoFacturaIdFactura != _cast.pedidoFacturaIdFactura) {
			return false;
		}
		
		if (pedidoFacturaIdFacturaModified != _cast.pedidoFacturaIdFacturaModified) {
			return false;
		}
		
		return true;
	}

	/**
	 * Method 'hashCode'
	 * 
	 * @return int
	 */
	public int hashCode()
	{
		int _hashCode = 0;
		if (productoIdProducto != null) {
			_hashCode = 29 * _hashCode + productoIdProducto.hashCode();
		}
		
		_hashCode = 29 * _hashCode + (productoIdProductoModified ? 1 : 0);
		_hashCode = 29 * _hashCode + cantidad;
		_hashCode = 29 * _hashCode + (cantidadNull ? 1 : 0);
		_hashCode = 29 * _hashCode + (cantidadModified ? 1 : 0);
		if (costoUnitario != null) {
			_hashCode = 29 * _hashCode + costoUnitario.hashCode();
		}
		
		_hashCode = 29 * _hashCode + (costoUnitarioModified ? 1 : 0);
		if (costoTotal != null) {
			_hashCode = 29 * _hashCode + costoTotal.hashCode();
		}
		
		_hashCode = 29 * _hashCode + (costoTotalModified ? 1 : 0);
		_hashCode = 29 * _hashCode + pedidoFacturaIdFactura;
		_hashCode = 29 * _hashCode + (pedidoFacturaIdFacturaModified ? 1 : 0);
		return _hashCode;
	}

	/**
	 * Method 'createPk'
	 * 
	 * @return ItemPk
	 */
	public ItemPk createPk()
	{
		return new ItemPk(productoIdProducto, pedidoFacturaIdFactura);
	}

	/**
	 * Method 'toString'
	 * 
	 * @return String
	 */
	public String toString()
	{
		StringBuffer ret = new StringBuffer();
		ret.append( "edu.co.sena.onlineshop.integracion.dto.Item: " );
		ret.append( "productoIdProducto=" + productoIdProducto );
		ret.append( ", cantidad=" + cantidad );
		ret.append( ", costoUnitario=" + costoUnitario );
		ret.append( ", costoTotal=" + costoTotal );
		ret.append( ", pedidoFacturaIdFactura=" + pedidoFacturaIdFactura );
		return ret.toString();
	}

}
