/*
 * This source file was generated by FireStorm/DAO.
 * 
 * If you purchase a full license for FireStorm/DAO you can customize this header file.
 * 
 * For more information please visit http://www.codefutures.com/products/firestorm
 */

package edu.co.sena.onlineshop.integracion.dto;

import edu.co.sena.onlineshop.integracion.dao.*;
import edu.co.sena.onlineshop.integracion.factory.*;
import edu.co.sena.onlineshop.integracion.exceptions.*;
import java.io.Serializable;
import java.util.*;

public class Pago implements Serializable
{
	/** 
	 * This attribute maps to the column FACTURA_ID_FACTURA in the pago table.
	 */
	protected int facturaIdFactura;

	/** 
	 * This attribute represents whether the attribute facturaIdFactura has been modified since being read from the database.
	 */
	protected boolean facturaIdFacturaModified = false;

	/** 
	 * This attribute maps to the column tipo_pago in the pago table.
	 */
	protected String tipoPago;

	/** 
	 * This attribute represents whether the attribute tipoPago has been modified since being read from the database.
	 */
	protected boolean tipoPagoModified = false;

	/** 
	 * This attribute maps to the column nume_cuenta in the pago table.
	 */
	protected String numeCuenta;

	/** 
	 * This attribute represents whether the attribute numeCuenta has been modified since being read from the database.
	 */
	protected boolean numeCuentaModified = false;

	/** 
	 * This attribute maps to the column numero_targeta in the pago table.
	 */
	protected int numeroTargeta;

	/** 
	 * This attribute represents whether the primitive attribute numeroTargeta is null.
	 */
	protected boolean numeroTargetaNull = true;

	/** 
	 * This attribute represents whether the attribute numeroTargeta has been modified since being read from the database.
	 */
	protected boolean numeroTargetaModified = false;

	/**
	 * Method 'Pago'
	 * 
	 */
	public Pago()
	{
	}

	/**
	 * Method 'getFacturaIdFactura'
	 * 
	 * @return int
	 */
	public int getFacturaIdFactura()
	{
		return facturaIdFactura;
	}

	/**
	 * Method 'setFacturaIdFactura'
	 * 
	 * @param facturaIdFactura
	 */
	public void setFacturaIdFactura(int facturaIdFactura)
	{
		this.facturaIdFactura = facturaIdFactura;
		this.facturaIdFacturaModified = true;
	}

	/** 
	 * Sets the value of facturaIdFacturaModified
	 */
	public void setFacturaIdFacturaModified(boolean facturaIdFacturaModified)
	{
		this.facturaIdFacturaModified = facturaIdFacturaModified;
	}

	/** 
	 * Gets the value of facturaIdFacturaModified
	 */
	public boolean isFacturaIdFacturaModified()
	{
		return facturaIdFacturaModified;
	}

	/**
	 * Method 'getTipoPago'
	 * 
	 * @return String
	 */
	public String getTipoPago()
	{
		return tipoPago;
	}

	/**
	 * Method 'setTipoPago'
	 * 
	 * @param tipoPago
	 */
	public void setTipoPago(String tipoPago)
	{
		this.tipoPago = tipoPago;
		this.tipoPagoModified = true;
	}

	/** 
	 * Sets the value of tipoPagoModified
	 */
	public void setTipoPagoModified(boolean tipoPagoModified)
	{
		this.tipoPagoModified = tipoPagoModified;
	}

	/** 
	 * Gets the value of tipoPagoModified
	 */
	public boolean isTipoPagoModified()
	{
		return tipoPagoModified;
	}

	/**
	 * Method 'getNumeCuenta'
	 * 
	 * @return String
	 */
	public String getNumeCuenta()
	{
		return numeCuenta;
	}

	/**
	 * Method 'setNumeCuenta'
	 * 
	 * @param numeCuenta
	 */
	public void setNumeCuenta(String numeCuenta)
	{
		this.numeCuenta = numeCuenta;
		this.numeCuentaModified = true;
	}

	/** 
	 * Sets the value of numeCuentaModified
	 */
	public void setNumeCuentaModified(boolean numeCuentaModified)
	{
		this.numeCuentaModified = numeCuentaModified;
	}

	/** 
	 * Gets the value of numeCuentaModified
	 */
	public boolean isNumeCuentaModified()
	{
		return numeCuentaModified;
	}

	/**
	 * Method 'getNumeroTargeta'
	 * 
	 * @return int
	 */
	public int getNumeroTargeta()
	{
		return numeroTargeta;
	}

	/**
	 * Method 'setNumeroTargeta'
	 * 
	 * @param numeroTargeta
	 */
	public void setNumeroTargeta(int numeroTargeta)
	{
		this.numeroTargeta = numeroTargeta;
		this.numeroTargetaNull = false;
		this.numeroTargetaModified = true;
	}

	/**
	 * Method 'setNumeroTargetaNull'
	 * 
	 * @param value
	 */
	public void setNumeroTargetaNull(boolean value)
	{
		this.numeroTargetaNull = value;
		this.numeroTargetaModified = true;
	}

	/**
	 * Method 'isNumeroTargetaNull'
	 * 
	 * @return boolean
	 */
	public boolean isNumeroTargetaNull()
	{
		return numeroTargetaNull;
	}

	/** 
	 * Sets the value of numeroTargetaModified
	 */
	public void setNumeroTargetaModified(boolean numeroTargetaModified)
	{
		this.numeroTargetaModified = numeroTargetaModified;
	}

	/** 
	 * Gets the value of numeroTargetaModified
	 */
	public boolean isNumeroTargetaModified()
	{
		return numeroTargetaModified;
	}

	/**
	 * Method 'equals'
	 * 
	 * @param _other
	 * @return boolean
	 */
	public boolean equals(Object _other)
	{
		if (_other == null) {
			return false;
		}
		
		if (_other == this) {
			return true;
		}
		
		if (!(_other instanceof Pago)) {
			return false;
		}
		
		final Pago _cast = (Pago) _other;
		if (facturaIdFactura != _cast.facturaIdFactura) {
			return false;
		}
		
		if (facturaIdFacturaModified != _cast.facturaIdFacturaModified) {
			return false;
		}
		
		if (tipoPago == null ? _cast.tipoPago != tipoPago : !tipoPago.equals( _cast.tipoPago )) {
			return false;
		}
		
		if (tipoPagoModified != _cast.tipoPagoModified) {
			return false;
		}
		
		if (numeCuenta == null ? _cast.numeCuenta != numeCuenta : !numeCuenta.equals( _cast.numeCuenta )) {
			return false;
		}
		
		if (numeCuentaModified != _cast.numeCuentaModified) {
			return false;
		}
		
		if (numeroTargeta != _cast.numeroTargeta) {
			return false;
		}
		
		if (numeroTargetaNull != _cast.numeroTargetaNull) {
			return false;
		}
		
		if (numeroTargetaModified != _cast.numeroTargetaModified) {
			return false;
		}
		
		return true;
	}

	/**
	 * Method 'hashCode'
	 * 
	 * @return int
	 */
	public int hashCode()
	{
		int _hashCode = 0;
		_hashCode = 29 * _hashCode + facturaIdFactura;
		_hashCode = 29 * _hashCode + (facturaIdFacturaModified ? 1 : 0);
		if (tipoPago != null) {
			_hashCode = 29 * _hashCode + tipoPago.hashCode();
		}
		
		_hashCode = 29 * _hashCode + (tipoPagoModified ? 1 : 0);
		if (numeCuenta != null) {
			_hashCode = 29 * _hashCode + numeCuenta.hashCode();
		}
		
		_hashCode = 29 * _hashCode + (numeCuentaModified ? 1 : 0);
		_hashCode = 29 * _hashCode + numeroTargeta;
		_hashCode = 29 * _hashCode + (numeroTargetaNull ? 1 : 0);
		_hashCode = 29 * _hashCode + (numeroTargetaModified ? 1 : 0);
		return _hashCode;
	}

	/**
	 * Method 'createPk'
	 * 
	 * @return PagoPk
	 */
	public PagoPk createPk()
	{
		return new PagoPk(facturaIdFactura);
	}

	/**
	 * Method 'toString'
	 * 
	 * @return String
	 */
	public String toString()
	{
		StringBuffer ret = new StringBuffer();
		ret.append( "edu.co.sena.onlineshop.integracion.dto.Pago: " );
		ret.append( "facturaIdFactura=" + facturaIdFactura );
		ret.append( ", tipoPago=" + tipoPago );
		ret.append( ", numeCuenta=" + numeCuenta );
		ret.append( ", numeroTargeta=" + numeroTargeta );
		return ret.toString();
	}

}
