/*
 * This source file was generated by FireStorm/DAO.
 * 
 * If you purchase a full license for FireStorm/DAO you can customize this header file.
 * 
 * For more information please visit http://www.codefutures.com/products/firestorm
 */

package edu.co.sena.onlineshop.negocio.examples;

import java.math.*;
import java.util.Date;
import java.util.Collection;
import edu.co.sena.onlineshop.integracion.dao.ProveedorDao;
import edu.co.sena.onlineshop.integracion.dto.Proveedor;
import edu.co.sena.onlineshop.integracion.exceptions.ProveedorDaoException;
import edu.co.sena.onlineshop.integracion.factory.ProveedorDaoFactory;

public class ProveedorDaoSample
{
	/**
	 * Method 'main'
	 * 
	 * @param arg
	 * @throws Exception
	 */
	public static void main(String[] arg) throws Exception
	{
		// Uncomment one of the lines below to test the generated code
		
		// findAll();
		// findWhereTipoDocumentoEquals("");
		// findWhereNumDocumentoEquals("");
		// findWhereNombreProveedorEquals("");
		// findWhereTelefonoEquals("");
		// findWhereDireccionEquals("");
		// findWhereCorreoEquals("");
		// findWhereDomicilioIddomicilioEquals(0);
	}

	/**
	 * Method 'findAll'
	 * 
	 */
	public static void findAll()
	{
		try {
			ProveedorDao _dao = getProveedorDao();
			Proveedor _result[] = _dao.findAll();
			for (int i=0; i<_result.length; i++ ) {
				display( _result[i] );
			}
		
		}
		catch (Exception _e) {
			_e.printStackTrace();
		}
		
	}

	/**
	 * Method 'findWhereTipoDocumentoEquals'
	 * 
	 * @param tipoDocumento
	 */
	public static void findWhereTipoDocumentoEquals(String tipoDocumento)
	{
		try {
			ProveedorDao _dao = getProveedorDao();
			Proveedor _result[] = _dao.findWhereTipoDocumentoEquals(tipoDocumento);
			for (int i=0; i<_result.length; i++ ) {
				display( _result[i] );
			}
		
		}
		catch (Exception _e) {
			_e.printStackTrace();
		}
		
	}

	/**
	 * Method 'findWhereNumDocumentoEquals'
	 * 
	 * @param numDocumento
	 */
	public static void findWhereNumDocumentoEquals(String numDocumento)
	{
		try {
			ProveedorDao _dao = getProveedorDao();
			Proveedor _result[] = _dao.findWhereNumDocumentoEquals(numDocumento);
			for (int i=0; i<_result.length; i++ ) {
				display( _result[i] );
			}
		
		}
		catch (Exception _e) {
			_e.printStackTrace();
		}
		
	}

	/**
	 * Method 'findWhereNombreProveedorEquals'
	 * 
	 * @param nombreProveedor
	 */
	public static void findWhereNombreProveedorEquals(String nombreProveedor)
	{
		try {
			ProveedorDao _dao = getProveedorDao();
			Proveedor _result[] = _dao.findWhereNombreProveedorEquals(nombreProveedor);
			for (int i=0; i<_result.length; i++ ) {
				display( _result[i] );
			}
		
		}
		catch (Exception _e) {
			_e.printStackTrace();
		}
		
	}

	/**
	 * Method 'findWhereTelefonoEquals'
	 * 
	 * @param telefono
	 */
	public static void findWhereTelefonoEquals(String telefono)
	{
		try {
			ProveedorDao _dao = getProveedorDao();
			Proveedor _result[] = _dao.findWhereTelefonoEquals(telefono);
			for (int i=0; i<_result.length; i++ ) {
				display( _result[i] );
			}
		
		}
		catch (Exception _e) {
			_e.printStackTrace();
		}
		
	}

	/**
	 * Method 'findWhereDireccionEquals'
	 * 
	 * @param direccion
	 */
	public static void findWhereDireccionEquals(String direccion)
	{
		try {
			ProveedorDao _dao = getProveedorDao();
			Proveedor _result[] = _dao.findWhereDireccionEquals(direccion);
			for (int i=0; i<_result.length; i++ ) {
				display( _result[i] );
			}
		
		}
		catch (Exception _e) {
			_e.printStackTrace();
		}
		
	}

	/**
	 * Method 'findWhereCorreoEquals'
	 * 
	 * @param correo
	 */
	public static void findWhereCorreoEquals(String correo)
	{
		try {
			ProveedorDao _dao = getProveedorDao();
			Proveedor _result[] = _dao.findWhereCorreoEquals(correo);
			for (int i=0; i<_result.length; i++ ) {
				display( _result[i] );
			}
		
		}
		catch (Exception _e) {
			_e.printStackTrace();
		}
		
	}

	/**
	 * Method 'findWhereDomicilioIddomicilioEquals'
	 * 
	 * @param domicilioIddomicilio
	 */
	public static void findWhereDomicilioIddomicilioEquals(int domicilioIddomicilio)
	{
		try {
			ProveedorDao _dao = getProveedorDao();
			Proveedor _result[] = _dao.findWhereDomicilioIddomicilioEquals(domicilioIddomicilio);
			for (int i=0; i<_result.length; i++ ) {
				display( _result[i] );
			}
		
		}
		catch (Exception _e) {
			_e.printStackTrace();
		}
		
	}

	/**
	 * Method 'getProveedorDao'
	 * 
	 * @return ProveedorDao
	 */
	public static ProveedorDao getProveedorDao()
	{
		return ProveedorDaoFactory.create();
	}

	/**
	 * Method 'display'
	 * 
	 * @param dto
	 */
	public static void display(Proveedor dto)
	{
		StringBuffer buf = new StringBuffer();
		buf.append( dto.getTipoDocumento() );
		buf.append( ", " );
		buf.append( dto.getNumDocumento() );
		buf.append( ", " );
		buf.append( dto.getNombreProveedor() );
		buf.append( ", " );
		buf.append( dto.getTelefono() );
		buf.append( ", " );
		buf.append( dto.getDireccion() );
		buf.append( ", " );
		buf.append( dto.getCorreo() );
		buf.append( ", " );
		buf.append( dto.getDomicilioIddomicilio() );
		System.out.println( buf.toString() );
	}

}
