/*
 * This source file was generated by FireStorm/DAO.
 * 
 * If you purchase a full license for FireStorm/DAO you can customize this header file.
 * 
 * For more information please visit http://www.codefutures.com/products/firestorm
 */

package edu.co.sena.onlineshop.integracion.dto;

import java.io.Serializable;
import java.math.BigDecimal;
import java.util.Date;

/** 
 * This class represents the primary key of the departamento table.
 */
public class DepartamentoPk implements Serializable
{
	protected int idDEPARTAMENTO;

	/** 
	 * This attribute represents whether the primitive attribute idDEPARTAMENTO is null.
	 */
	protected boolean idDEPARTAMENTONull;

	/** 
	 * Sets the value of idDEPARTAMENTO
	 */
	public void setIdDEPARTAMENTO(int idDEPARTAMENTO)
	{
		this.idDEPARTAMENTO = idDEPARTAMENTO;
	}

	/** 
	 * Gets the value of idDEPARTAMENTO
	 */
	public int getIdDEPARTAMENTO()
	{
		return idDEPARTAMENTO;
	}

	/**
	 * Method 'DepartamentoPk'
	 * 
	 */
	public DepartamentoPk()
	{
	}

	/**
	 * Method 'DepartamentoPk'
	 * 
	 * @param idDEPARTAMENTO
	 */
	public DepartamentoPk(final int idDEPARTAMENTO)
	{
		this.idDEPARTAMENTO = idDEPARTAMENTO;
	}

	/** 
	 * Sets the value of idDEPARTAMENTONull
	 */
	public void setIdDEPARTAMENTONull(boolean idDEPARTAMENTONull)
	{
		this.idDEPARTAMENTONull = idDEPARTAMENTONull;
	}

	/** 
	 * Gets the value of idDEPARTAMENTONull
	 */
	public boolean isIdDEPARTAMENTONull()
	{
		return idDEPARTAMENTONull;
	}

	/**
	 * Method 'equals'
	 * 
	 * @param _other
	 * @return boolean
	 */
	public boolean equals(Object _other)
	{
		if (_other == null) {
			return false;
		}
		
		if (_other == this) {
			return true;
		}
		
		if (!(_other instanceof DepartamentoPk)) {
			return false;
		}
		
		final DepartamentoPk _cast = (DepartamentoPk) _other;
		if (idDEPARTAMENTO != _cast.idDEPARTAMENTO) {
			return false;
		}
		
		if (idDEPARTAMENTONull != _cast.idDEPARTAMENTONull) {
			return false;
		}
		
		return true;
	}

	/**
	 * Method 'hashCode'
	 * 
	 * @return int
	 */
	public int hashCode()
	{
		int _hashCode = 0;
		_hashCode = 29 * _hashCode + idDEPARTAMENTO;
		_hashCode = 29 * _hashCode + (idDEPARTAMENTONull ? 1 : 0);
		return _hashCode;
	}

	/**
	 * Method 'toString'
	 * 
	 * @return String
	 */
	public String toString()
	{
		StringBuffer ret = new StringBuffer();
		ret.append( "edu.co.sena.onlineshop.integracion.dto.DepartamentoPk: " );
		ret.append( "idDEPARTAMENTO=" + idDEPARTAMENTO );
		return ret.toString();
	}

}
