/*
 * This source file was generated by FireStorm/DAO.
 * 
 * If you purchase a full license for FireStorm/DAO you can customize this header file.
 * 
 * For more information please visit http://www.codefutures.com/products/firestorm
 */

package edu.co.sena.onlineshop.integracion.dto;

import edu.co.sena.onlineshop.integracion.dao.*;
import edu.co.sena.onlineshop.integracion.factory.*;
import edu.co.sena.onlineshop.integracion.exceptions.*;
import java.io.Serializable;
import java.util.*;

public class DomicilioCuentas implements Serializable
{
	/** 
	 * This attribute maps to the column direccion in the domicilio_cuentas table.
	 */
	protected String direccion;

	/** 
	 * This attribute maps to the column telefono in the domicilio_cuentas table.
	 */
	protected String telefono;

	/** 
	 * This attribute maps to the column barrio in the domicilio_cuentas table.
	 */
	protected String barrio;

	/** 
	 * This attribute maps to the column localidad in the domicilio_cuentas table.
	 */
	protected String localidad;

	/** 
	 * This attribute maps to the column CORREO_POSTAL in the domicilio_cuentas table.
	 */
	protected String correoPostal;

	/** 
	 * This attribute maps to the column MUNICIPIO_idMUNICIPIO in the domicilio_cuentas table.
	 */
	protected int municipioIdmunicipio;

	/** 
	 * This attribute maps to the column CUENTA_NUMERO_DOCUMENTO in the domicilio_cuentas table.
	 */
	protected String cuentaNumeroDocumento;

	/** 
	 * This attribute maps to the column CUENTA_TIPO_DOCUMENTO in the domicilio_cuentas table.
	 */
	protected String cuentaTipoDocumento;

	/**
	 * Method 'DomicilioCuentas'
	 * 
	 */
	public DomicilioCuentas()
	{
	}

	/**
	 * Method 'getDireccion'
	 * 
	 * @return String
	 */
	public String getDireccion()
	{
		return direccion;
	}

	/**
	 * Method 'setDireccion'
	 * 
	 * @param direccion
	 */
	public void setDireccion(String direccion)
	{
		this.direccion = direccion;
	}

	/**
	 * Method 'getTelefono'
	 * 
	 * @return String
	 */
	public String getTelefono()
	{
		return telefono;
	}

	/**
	 * Method 'setTelefono'
	 * 
	 * @param telefono
	 */
	public void setTelefono(String telefono)
	{
		this.telefono = telefono;
	}

	/**
	 * Method 'getBarrio'
	 * 
	 * @return String
	 */
	public String getBarrio()
	{
		return barrio;
	}

	/**
	 * Method 'setBarrio'
	 * 
	 * @param barrio
	 */
	public void setBarrio(String barrio)
	{
		this.barrio = barrio;
	}

	/**
	 * Method 'getLocalidad'
	 * 
	 * @return String
	 */
	public String getLocalidad()
	{
		return localidad;
	}

	/**
	 * Method 'setLocalidad'
	 * 
	 * @param localidad
	 */
	public void setLocalidad(String localidad)
	{
		this.localidad = localidad;
	}

	/**
	 * Method 'getCorreoPostal'
	 * 
	 * @return String
	 */
	public String getCorreoPostal()
	{
		return correoPostal;
	}

	/**
	 * Method 'setCorreoPostal'
	 * 
	 * @param correoPostal
	 */
	public void setCorreoPostal(String correoPostal)
	{
		this.correoPostal = correoPostal;
	}

	/**
	 * Method 'getMunicipioIdmunicipio'
	 * 
	 * @return int
	 */
	public int getMunicipioIdmunicipio()
	{
		return municipioIdmunicipio;
	}

	/**
	 * Method 'setMunicipioIdmunicipio'
	 * 
	 * @param municipioIdmunicipio
	 */
	public void setMunicipioIdmunicipio(int municipioIdmunicipio)
	{
		this.municipioIdmunicipio = municipioIdmunicipio;
	}

	/**
	 * Method 'getCuentaNumeroDocumento'
	 * 
	 * @return String
	 */
	public String getCuentaNumeroDocumento()
	{
		return cuentaNumeroDocumento;
	}

	/**
	 * Method 'setCuentaNumeroDocumento'
	 * 
	 * @param cuentaNumeroDocumento
	 */
	public void setCuentaNumeroDocumento(String cuentaNumeroDocumento)
	{
		this.cuentaNumeroDocumento = cuentaNumeroDocumento;
	}

	/**
	 * Method 'getCuentaTipoDocumento'
	 * 
	 * @return String
	 */
	public String getCuentaTipoDocumento()
	{
		return cuentaTipoDocumento;
	}

	/**
	 * Method 'setCuentaTipoDocumento'
	 * 
	 * @param cuentaTipoDocumento
	 */
	public void setCuentaTipoDocumento(String cuentaTipoDocumento)
	{
		this.cuentaTipoDocumento = cuentaTipoDocumento;
	}

	/**
	 * Method 'equals'
	 * 
	 * @param _other
	 * @return boolean
	 */
	public boolean equals(Object _other)
	{
		if (_other == null) {
			return false;
		}
		
		if (_other == this) {
			return true;
		}
		
		if (!(_other instanceof DomicilioCuentas)) {
			return false;
		}
		
		final DomicilioCuentas _cast = (DomicilioCuentas) _other;
		if (direccion == null ? _cast.direccion != direccion : !direccion.equals( _cast.direccion )) {
			return false;
		}
		
		if (telefono == null ? _cast.telefono != telefono : !telefono.equals( _cast.telefono )) {
			return false;
		}
		
		if (barrio == null ? _cast.barrio != barrio : !barrio.equals( _cast.barrio )) {
			return false;
		}
		
		if (localidad == null ? _cast.localidad != localidad : !localidad.equals( _cast.localidad )) {
			return false;
		}
		
		if (correoPostal == null ? _cast.correoPostal != correoPostal : !correoPostal.equals( _cast.correoPostal )) {
			return false;
		}
		
		if (municipioIdmunicipio != _cast.municipioIdmunicipio) {
			return false;
		}
		
		if (cuentaNumeroDocumento == null ? _cast.cuentaNumeroDocumento != cuentaNumeroDocumento : !cuentaNumeroDocumento.equals( _cast.cuentaNumeroDocumento )) {
			return false;
		}
		
		if (cuentaTipoDocumento == null ? _cast.cuentaTipoDocumento != cuentaTipoDocumento : !cuentaTipoDocumento.equals( _cast.cuentaTipoDocumento )) {
			return false;
		}
		
		return true;
	}

	/**
	 * Method 'hashCode'
	 * 
	 * @return int
	 */
	public int hashCode()
	{
		int _hashCode = 0;
		if (direccion != null) {
			_hashCode = 29 * _hashCode + direccion.hashCode();
		}
		
		if (telefono != null) {
			_hashCode = 29 * _hashCode + telefono.hashCode();
		}
		
		if (barrio != null) {
			_hashCode = 29 * _hashCode + barrio.hashCode();
		}
		
		if (localidad != null) {
			_hashCode = 29 * _hashCode + localidad.hashCode();
		}
		
		if (correoPostal != null) {
			_hashCode = 29 * _hashCode + correoPostal.hashCode();
		}
		
		_hashCode = 29 * _hashCode + municipioIdmunicipio;
		if (cuentaNumeroDocumento != null) {
			_hashCode = 29 * _hashCode + cuentaNumeroDocumento.hashCode();
		}
		
		if (cuentaTipoDocumento != null) {
			_hashCode = 29 * _hashCode + cuentaTipoDocumento.hashCode();
		}
		
		return _hashCode;
	}

	/**
	 * Method 'createPk'
	 * 
	 * @return DomicilioCuentasPk
	 */
	public DomicilioCuentasPk createPk()
	{
		return new DomicilioCuentasPk(cuentaNumeroDocumento, cuentaTipoDocumento);
	}

	/**
	 * Method 'toString'
	 * 
	 * @return String
	 */
	public String toString()
	{
		StringBuffer ret = new StringBuffer();
		ret.append( "edu.co.sena.onlineshop.integracion.dto.DomicilioCuentas: " );
		ret.append( "direccion=" + direccion );
		ret.append( ", telefono=" + telefono );
		ret.append( ", barrio=" + barrio );
		ret.append( ", localidad=" + localidad );
		ret.append( ", correoPostal=" + correoPostal );
		ret.append( ", municipioIdmunicipio=" + municipioIdmunicipio );
		ret.append( ", cuentaNumeroDocumento=" + cuentaNumeroDocumento );
		ret.append( ", cuentaTipoDocumento=" + cuentaTipoDocumento );
		return ret.toString();
	}

}
