/*
 * This source file was generated by FireStorm/DAO.
 * 
 * If you purchase a full license for FireStorm/DAO you can customize this header file.
 * 
 * For more information please visit http://www.codefutures.com/products/firestorm
 */

package edu.co.sena.onlineshop.integracion.dto;

import edu.co.sena.onlineshop.integracion.dao.*;
import edu.co.sena.onlineshop.integracion.factory.*;
import edu.co.sena.onlineshop.integracion.exceptions.*;
import java.io.Serializable;
import java.util.*;

public class InventarioCompras implements Serializable
{
	/** 
	 * This attribute maps to the column ID_INVENTARIO in the inventario_compras table.
	 */
	protected int idInventario;

	/** 
	 * This attribute maps to the column PRODUCTO_ID_PRODUCTO in the inventario_compras table.
	 */
	protected String productoIdProducto;

	/** 
	 * This attribute maps to the column CAN_PRO_COMPRADO in the inventario_compras table.
	 */
	protected int canProComprado;

	/** 
	 * This attribute represents whether the primitive attribute canProComprado is null.
	 */
	protected boolean canProCompradoNull = true;

	/** 
	 * This attribute maps to the column FECHA_COMPRA in the inventario_compras table.
	 */
	protected String fechaCompra;

	/** 
	 * This attribute maps to the column PROVEEDOR_TIPO_DOCUMENTO in the inventario_compras table.
	 */
	protected String proveedorTipoDocumento;

	/** 
	 * This attribute maps to the column PROVEEDOR_NUM_DOCUMENTO in the inventario_compras table.
	 */
	protected String proveedorNumDocumento;

	/**
	 * Method 'InventarioCompras'
	 * 
	 */
	public InventarioCompras()
	{
	}

	/**
	 * Method 'getIdInventario'
	 * 
	 * @return int
	 */
	public int getIdInventario()
	{
		return idInventario;
	}

	/**
	 * Method 'setIdInventario'
	 * 
	 * @param idInventario
	 */
	public void setIdInventario(int idInventario)
	{
		this.idInventario = idInventario;
	}

	/**
	 * Method 'getProductoIdProducto'
	 * 
	 * @return String
	 */
	public String getProductoIdProducto()
	{
		return productoIdProducto;
	}

	/**
	 * Method 'setProductoIdProducto'
	 * 
	 * @param productoIdProducto
	 */
	public void setProductoIdProducto(String productoIdProducto)
	{
		this.productoIdProducto = productoIdProducto;
	}

	/**
	 * Method 'getCanProComprado'
	 * 
	 * @return int
	 */
	public int getCanProComprado()
	{
		return canProComprado;
	}

	/**
	 * Method 'setCanProComprado'
	 * 
	 * @param canProComprado
	 */
	public void setCanProComprado(int canProComprado)
	{
		this.canProComprado = canProComprado;
		this.canProCompradoNull = false;
	}

	/**
	 * Method 'setCanProCompradoNull'
	 * 
	 * @param value
	 */
	public void setCanProCompradoNull(boolean value)
	{
		this.canProCompradoNull = value;
	}

	/**
	 * Method 'isCanProCompradoNull'
	 * 
	 * @return boolean
	 */
	public boolean isCanProCompradoNull()
	{
		return canProCompradoNull;
	}

	/**
	 * Method 'getFechaCompra'
	 * 
	 * @return String
	 */
	public String getFechaCompra()
	{
		return fechaCompra;
	}

	/**
	 * Method 'setFechaCompra'
	 * 
	 * @param fechaCompra
	 */
	public void setFechaCompra(String fechaCompra)
	{
		this.fechaCompra = fechaCompra;
	}

	/**
	 * Method 'getProveedorTipoDocumento'
	 * 
	 * @return String
	 */
	public String getProveedorTipoDocumento()
	{
		return proveedorTipoDocumento;
	}

	/**
	 * Method 'setProveedorTipoDocumento'
	 * 
	 * @param proveedorTipoDocumento
	 */
	public void setProveedorTipoDocumento(String proveedorTipoDocumento)
	{
		this.proveedorTipoDocumento = proveedorTipoDocumento;
	}

	/**
	 * Method 'getProveedorNumDocumento'
	 * 
	 * @return String
	 */
	public String getProveedorNumDocumento()
	{
		return proveedorNumDocumento;
	}

	/**
	 * Method 'setProveedorNumDocumento'
	 * 
	 * @param proveedorNumDocumento
	 */
	public void setProveedorNumDocumento(String proveedorNumDocumento)
	{
		this.proveedorNumDocumento = proveedorNumDocumento;
	}

	/**
	 * Method 'equals'
	 * 
	 * @param _other
	 * @return boolean
	 */
	public boolean equals(Object _other)
	{
		if (_other == null) {
			return false;
		}
		
		if (_other == this) {
			return true;
		}
		
		if (!(_other instanceof InventarioCompras)) {
			return false;
		}
		
		final InventarioCompras _cast = (InventarioCompras) _other;
		if (idInventario != _cast.idInventario) {
			return false;
		}
		
		if (productoIdProducto == null ? _cast.productoIdProducto != productoIdProducto : !productoIdProducto.equals( _cast.productoIdProducto )) {
			return false;
		}
		
		if (canProComprado != _cast.canProComprado) {
			return false;
		}
		
		if (canProCompradoNull != _cast.canProCompradoNull) {
			return false;
		}
		
		if (fechaCompra == null ? _cast.fechaCompra != fechaCompra : !fechaCompra.equals( _cast.fechaCompra )) {
			return false;
		}
		
		if (proveedorTipoDocumento == null ? _cast.proveedorTipoDocumento != proveedorTipoDocumento : !proveedorTipoDocumento.equals( _cast.proveedorTipoDocumento )) {
			return false;
		}
		
		if (proveedorNumDocumento == null ? _cast.proveedorNumDocumento != proveedorNumDocumento : !proveedorNumDocumento.equals( _cast.proveedorNumDocumento )) {
			return false;
		}
		
		return true;
	}

	/**
	 * Method 'hashCode'
	 * 
	 * @return int
	 */
	public int hashCode()
	{
		int _hashCode = 0;
		_hashCode = 29 * _hashCode + idInventario;
		if (productoIdProducto != null) {
			_hashCode = 29 * _hashCode + productoIdProducto.hashCode();
		}
		
		_hashCode = 29 * _hashCode + canProComprado;
		_hashCode = 29 * _hashCode + (canProCompradoNull ? 1 : 0);
		if (fechaCompra != null) {
			_hashCode = 29 * _hashCode + fechaCompra.hashCode();
		}
		
		if (proveedorTipoDocumento != null) {
			_hashCode = 29 * _hashCode + proveedorTipoDocumento.hashCode();
		}
		
		if (proveedorNumDocumento != null) {
			_hashCode = 29 * _hashCode + proveedorNumDocumento.hashCode();
		}
		
		return _hashCode;
	}

	/**
	 * Method 'createPk'
	 * 
	 * @return InventarioComprasPk
	 */
	public InventarioComprasPk createPk()
	{
		return new InventarioComprasPk(idInventario, productoIdProducto, proveedorTipoDocumento, proveedorNumDocumento);
	}

	/**
	 * Method 'toString'
	 * 
	 * @return String
	 */
	public String toString()
	{
		StringBuffer ret = new StringBuffer();
		ret.append( "edu.co.sena.onlineshop.integracion.dto.InventarioCompras: " );
		ret.append( "idInventario=" + idInventario );
		ret.append( ", productoIdProducto=" + productoIdProducto );
		ret.append( ", canProComprado=" + canProComprado );
		ret.append( ", fechaCompra=" + fechaCompra );
		ret.append( ", proveedorTipoDocumento=" + proveedorTipoDocumento );
		ret.append( ", proveedorNumDocumento=" + proveedorNumDocumento );
		return ret.toString();
	}

}
