/*
 * This source file was generated by FireStorm/DAO.
 * 
 * If you purchase a full license for FireStorm/DAO you can customize this header file.
 * 
 * For more information please visit http://www.codefutures.com/products/firestorm
 */

package edu.co.sena.onlineshop.integracion.dto;

import edu.co.sena.onlineshop.integracion.dao.*;
import edu.co.sena.onlineshop.integracion.factory.*;
import edu.co.sena.onlineshop.integracion.exceptions.*;
import java.io.Serializable;
import java.util.*;

public class Municipio implements Serializable
{
	/** 
	 * This attribute maps to the column idMUNICIPIO in the municipio table.
	 */
	protected int idMUNICIPIO;

	/** 
	 * This attribute maps to the column NOMBRE_MUNICIPIO in the municipio table.
	 */
	protected String nombreMunicipio;

	/** 
	 * This attribute maps to the column DEPARTAMENTO_idDEPARTAMENTO in the municipio table.
	 */
	protected int departamentoIddepartamento;

	/**
	 * Method 'Municipio'
	 * 
	 */
	public Municipio()
	{
	}

	/**
	 * Method 'getIdMUNICIPIO'
	 * 
	 * @return int
	 */
	public int getIdMUNICIPIO()
	{
		return idMUNICIPIO;
	}

	/**
	 * Method 'setIdMUNICIPIO'
	 * 
	 * @param idMUNICIPIO
	 */
	public void setIdMUNICIPIO(int idMUNICIPIO)
	{
		this.idMUNICIPIO = idMUNICIPIO;
	}

	/**
	 * Method 'getNombreMunicipio'
	 * 
	 * @return String
	 */
	public String getNombreMunicipio()
	{
		return nombreMunicipio;
	}

	/**
	 * Method 'setNombreMunicipio'
	 * 
	 * @param nombreMunicipio
	 */
	public void setNombreMunicipio(String nombreMunicipio)
	{
		this.nombreMunicipio = nombreMunicipio;
	}

	/**
	 * Method 'getDepartamentoIddepartamento'
	 * 
	 * @return int
	 */
	public int getDepartamentoIddepartamento()
	{
		return departamentoIddepartamento;
	}

	/**
	 * Method 'setDepartamentoIddepartamento'
	 * 
	 * @param departamentoIddepartamento
	 */
	public void setDepartamentoIddepartamento(int departamentoIddepartamento)
	{
		this.departamentoIddepartamento = departamentoIddepartamento;
	}

	/**
	 * Method 'equals'
	 * 
	 * @param _other
	 * @return boolean
	 */
	public boolean equals(Object _other)
	{
		if (_other == null) {
			return false;
		}
		
		if (_other == this) {
			return true;
		}
		
		if (!(_other instanceof Municipio)) {
			return false;
		}
		
		final Municipio _cast = (Municipio) _other;
		if (idMUNICIPIO != _cast.idMUNICIPIO) {
			return false;
		}
		
		if (nombreMunicipio == null ? _cast.nombreMunicipio != nombreMunicipio : !nombreMunicipio.equals( _cast.nombreMunicipio )) {
			return false;
		}
		
		if (departamentoIddepartamento != _cast.departamentoIddepartamento) {
			return false;
		}
		
		return true;
	}

	/**
	 * Method 'hashCode'
	 * 
	 * @return int
	 */
	public int hashCode()
	{
		int _hashCode = 0;
		_hashCode = 29 * _hashCode + idMUNICIPIO;
		if (nombreMunicipio != null) {
			_hashCode = 29 * _hashCode + nombreMunicipio.hashCode();
		}
		
		_hashCode = 29 * _hashCode + departamentoIddepartamento;
		return _hashCode;
	}

	/**
	 * Method 'createPk'
	 * 
	 * @return MunicipioPk
	 */
	public MunicipioPk createPk()
	{
		return new MunicipioPk(idMUNICIPIO);
	}

	/**
	 * Method 'toString'
	 * 
	 * @return String
	 */
	public String toString()
	{
		StringBuffer ret = new StringBuffer();
		ret.append( "edu.co.sena.onlineshop.integracion.dto.Municipio: " );
		ret.append( "idMUNICIPIO=" + idMUNICIPIO );
		ret.append( ", nombreMunicipio=" + nombreMunicipio );
		ret.append( ", departamentoIddepartamento=" + departamentoIddepartamento );
		return ret.toString();
	}

}
