/*
 * This source file was generated by FireStorm/DAO.
 * 
 * If you purchase a full license for FireStorm/DAO you can customize this header file.
 * 
 * For more information please visit http://www.codefutures.com/products/firestorm
 */

package edu.co.sena.onlineshop.integracion.dto;

import edu.co.sena.onlineshop.integracion.dao.*;
import edu.co.sena.onlineshop.integracion.factory.*;
import edu.co.sena.onlineshop.integracion.exceptions.*;
import java.io.Serializable;
import java.util.*;
import java.util.Date;

public class Producto implements Serializable
{
	/** 
	 * This attribute maps to the column ID_PRODUCTO in the producto table.
	 */
	protected String idProducto;

	/** 
	 * This attribute maps to the column NOMBRE_PRODUCTO in the producto table.
	 */
	protected String nombreProducto;

	/** 
	 * This attribute maps to the column PRECIO in the producto table.
	 */
	protected double precio;

	/** 
	 * This attribute maps to the column IMAGEN in the producto table.
	 */
	protected byte[] imagen;

	/** 
	 * This attribute maps to the column CANTIDAD in the producto table.
	 */
	protected float cantidad;

	/** 
	 * This attribute represents whether the primitive attribute cantidad is null.
	 */
	protected boolean cantidadNull = true;

	/** 
	 * This attribute maps to the column ACTIVO in the producto table.
	 */
	protected short activo;

	/** 
	 * This attribute maps to the column FECHA_CREACION in the producto table.
	 */
	protected Date fechaCreacion;

	/** 
	 * This attribute maps to the column USUARIO_CREACION in the producto table.
	 */
	protected String usuarioCreacion;

	/** 
	 * This attribute maps to the column FECHA_ULTIMA_MODIFICACION in the producto table.
	 */
	protected Date fechaUltimaModificacion;

	/** 
	 * This attribute maps to the column USUARIO_ULTIMA_MODIFICACION in the producto table.
	 */
	protected String usuarioUltimaModificacion;

	/** 
	 * This attribute maps to the column CATEGORIA_ID_CATEGORIA in the producto table.
	 */
	protected int categoriaIdCategoria;

	/** 
	 * This attribute maps to the column CATALOGO_ID_CATALOGO in the producto table.
	 */
	protected int catalogoIdCatalogo;

	/**
	 * Method 'Producto'
	 * 
	 */
	public Producto()
	{
	}

	/**
	 * Method 'getIdProducto'
	 * 
	 * @return String
	 */
	public String getIdProducto()
	{
		return idProducto;
	}

	/**
	 * Method 'setIdProducto'
	 * 
	 * @param idProducto
	 */
	public void setIdProducto(String idProducto)
	{
		this.idProducto = idProducto;
	}

	/**
	 * Method 'getNombreProducto'
	 * 
	 * @return String
	 */
	public String getNombreProducto()
	{
		return nombreProducto;
	}

	/**
	 * Method 'setNombreProducto'
	 * 
	 * @param nombreProducto
	 */
	public void setNombreProducto(String nombreProducto)
	{
		this.nombreProducto = nombreProducto;
	}

	/**
	 * Method 'getPrecio'
	 * 
	 * @return double
	 */
	public double getPrecio()
	{
		return precio;
	}

	/**
	 * Method 'setPrecio'
	 * 
	 * @param precio
	 */
	public void setPrecio(double precio)
	{
		this.precio = precio;
	}

	/**
	 * Method 'getImagen'
	 * 
	 * @return byte[]
	 */
	public byte[] getImagen()
	{
		return imagen;
	}

	/**
	 * Method 'setImagen'
	 * 
	 * @param imagen
	 */
	public void setImagen(byte[] imagen)
	{
		this.imagen = imagen;
	}

	/**
	 * Method 'getCantidad'
	 * 
	 * @return float
	 */
	public float getCantidad()
	{
		return cantidad;
	}

	/**
	 * Method 'setCantidad'
	 * 
	 * @param cantidad
	 */
	public void setCantidad(float cantidad)
	{
		this.cantidad = cantidad;
		this.cantidadNull = false;
	}

	/**
	 * Method 'setCantidadNull'
	 * 
	 * @param value
	 */
	public void setCantidadNull(boolean value)
	{
		this.cantidadNull = value;
	}

	/**
	 * Method 'isCantidadNull'
	 * 
	 * @return boolean
	 */
	public boolean isCantidadNull()
	{
		return cantidadNull;
	}

	/**
	 * Method 'getActivo'
	 * 
	 * @return short
	 */
	public short getActivo()
	{
		return activo;
	}

	/**
	 * Method 'setActivo'
	 * 
	 * @param activo
	 */
	public void setActivo(short activo)
	{
		this.activo = activo;
	}

	/**
	 * Method 'getFechaCreacion'
	 * 
	 * @return Date
	 */
	public Date getFechaCreacion()
	{
		return fechaCreacion;
	}

	/**
	 * Method 'setFechaCreacion'
	 * 
	 * @param fechaCreacion
	 */
	public void setFechaCreacion(Date fechaCreacion)
	{
		this.fechaCreacion = fechaCreacion;
	}

	/**
	 * Method 'getUsuarioCreacion'
	 * 
	 * @return String
	 */
	public String getUsuarioCreacion()
	{
		return usuarioCreacion;
	}

	/**
	 * Method 'setUsuarioCreacion'
	 * 
	 * @param usuarioCreacion
	 */
	public void setUsuarioCreacion(String usuarioCreacion)
	{
		this.usuarioCreacion = usuarioCreacion;
	}

	/**
	 * Method 'getFechaUltimaModificacion'
	 * 
	 * @return Date
	 */
	public Date getFechaUltimaModificacion()
	{
		return fechaUltimaModificacion;
	}

	/**
	 * Method 'setFechaUltimaModificacion'
	 * 
	 * @param fechaUltimaModificacion
	 */
	public void setFechaUltimaModificacion(Date fechaUltimaModificacion)
	{
		this.fechaUltimaModificacion = fechaUltimaModificacion;
	}

	/**
	 * Method 'getUsuarioUltimaModificacion'
	 * 
	 * @return String
	 */
	public String getUsuarioUltimaModificacion()
	{
		return usuarioUltimaModificacion;
	}

	/**
	 * Method 'setUsuarioUltimaModificacion'
	 * 
	 * @param usuarioUltimaModificacion
	 */
	public void setUsuarioUltimaModificacion(String usuarioUltimaModificacion)
	{
		this.usuarioUltimaModificacion = usuarioUltimaModificacion;
	}

	/**
	 * Method 'getCategoriaIdCategoria'
	 * 
	 * @return int
	 */
	public int getCategoriaIdCategoria()
	{
		return categoriaIdCategoria;
	}

	/**
	 * Method 'setCategoriaIdCategoria'
	 * 
	 * @param categoriaIdCategoria
	 */
	public void setCategoriaIdCategoria(int categoriaIdCategoria)
	{
		this.categoriaIdCategoria = categoriaIdCategoria;
	}

	/**
	 * Method 'getCatalogoIdCatalogo'
	 * 
	 * @return int
	 */
	public int getCatalogoIdCatalogo()
	{
		return catalogoIdCatalogo;
	}

	/**
	 * Method 'setCatalogoIdCatalogo'
	 * 
	 * @param catalogoIdCatalogo
	 */
	public void setCatalogoIdCatalogo(int catalogoIdCatalogo)
	{
		this.catalogoIdCatalogo = catalogoIdCatalogo;
	}

	/**
	 * Method 'equals'
	 * 
	 * @param _other
	 * @return boolean
	 */
	public boolean equals(Object _other)
	{
		if (_other == null) {
			return false;
		}
		
		if (_other == this) {
			return true;
		}
		
		if (!(_other instanceof Producto)) {
			return false;
		}
		
		final Producto _cast = (Producto) _other;
		if (idProducto == null ? _cast.idProducto != idProducto : !idProducto.equals( _cast.idProducto )) {
			return false;
		}
		
		if (nombreProducto == null ? _cast.nombreProducto != nombreProducto : !nombreProducto.equals( _cast.nombreProducto )) {
			return false;
		}
		
		if (precio != _cast.precio) {
			return false;
		}
		
		if (imagen == null ? _cast.imagen != imagen : !imagen.equals( _cast.imagen )) {
			return false;
		}
		
		if (cantidad != _cast.cantidad) {
			return false;
		}
		
		if (cantidadNull != _cast.cantidadNull) {
			return false;
		}
		
		if (activo != _cast.activo) {
			return false;
		}
		
		if (fechaCreacion == null ? _cast.fechaCreacion != fechaCreacion : !fechaCreacion.equals( _cast.fechaCreacion )) {
			return false;
		}
		
		if (usuarioCreacion == null ? _cast.usuarioCreacion != usuarioCreacion : !usuarioCreacion.equals( _cast.usuarioCreacion )) {
			return false;
		}
		
		if (fechaUltimaModificacion == null ? _cast.fechaUltimaModificacion != fechaUltimaModificacion : !fechaUltimaModificacion.equals( _cast.fechaUltimaModificacion )) {
			return false;
		}
		
		if (usuarioUltimaModificacion == null ? _cast.usuarioUltimaModificacion != usuarioUltimaModificacion : !usuarioUltimaModificacion.equals( _cast.usuarioUltimaModificacion )) {
			return false;
		}
		
		if (categoriaIdCategoria != _cast.categoriaIdCategoria) {
			return false;
		}
		
		if (catalogoIdCatalogo != _cast.catalogoIdCatalogo) {
			return false;
		}
		
		return true;
	}

	/**
	 * Method 'hashCode'
	 * 
	 * @return int
	 */
	public int hashCode()
	{
		int _hashCode = 0;
		if (idProducto != null) {
			_hashCode = 29 * _hashCode + idProducto.hashCode();
		}
		
		if (nombreProducto != null) {
			_hashCode = 29 * _hashCode + nombreProducto.hashCode();
		}
		
		long temp_precio = Double.doubleToLongBits(precio);
		_hashCode = 29 * _hashCode + (int) (temp_precio ^ (temp_precio >>> 32));
		if (imagen != null) {
			_hashCode = 29 * _hashCode + imagen.hashCode();
		}
		
		_hashCode = 29 * _hashCode + Float.floatToIntBits(cantidad);
		_hashCode = 29 * _hashCode + (cantidadNull ? 1 : 0);
		_hashCode = 29 * _hashCode + (int) activo;
		if (fechaCreacion != null) {
			_hashCode = 29 * _hashCode + fechaCreacion.hashCode();
		}
		
		if (usuarioCreacion != null) {
			_hashCode = 29 * _hashCode + usuarioCreacion.hashCode();
		}
		
		if (fechaUltimaModificacion != null) {
			_hashCode = 29 * _hashCode + fechaUltimaModificacion.hashCode();
		}
		
		if (usuarioUltimaModificacion != null) {
			_hashCode = 29 * _hashCode + usuarioUltimaModificacion.hashCode();
		}
		
		_hashCode = 29 * _hashCode + categoriaIdCategoria;
		_hashCode = 29 * _hashCode + catalogoIdCatalogo;
		return _hashCode;
	}

	/**
	 * Method 'createPk'
	 * 
	 * @return ProductoPk
	 */
	public ProductoPk createPk()
	{
		return new ProductoPk(idProducto);
	}

	/**
	 * Method 'toString'
	 * 
	 * @return String
	 */
	public String toString()
	{
		StringBuffer ret = new StringBuffer();
		ret.append( "edu.co.sena.onlineshop.integracion.dto.Producto: " );
		ret.append( "idProducto=" + idProducto );
		ret.append( ", nombreProducto=" + nombreProducto );
		ret.append( ", precio=" + precio );
		ret.append( ", imagen=" + imagen );
		ret.append( ", cantidad=" + cantidad );
		ret.append( ", activo=" + activo );
		ret.append( ", fechaCreacion=" + fechaCreacion );
		ret.append( ", usuarioCreacion=" + usuarioCreacion );
		ret.append( ", fechaUltimaModificacion=" + fechaUltimaModificacion );
		ret.append( ", usuarioUltimaModificacion=" + usuarioUltimaModificacion );
		ret.append( ", categoriaIdCategoria=" + categoriaIdCategoria );
		ret.append( ", catalogoIdCatalogo=" + catalogoIdCatalogo );
		return ret.toString();
	}

}
