/*
 * This source file was generated by FireStorm/DAO.
 * 
 * If you purchase a full license for FireStorm/DAO you can customize this header file.
 * 
 * For more information please visit http://www.codefutures.com/products/firestorm
 */

package edu.co.sena.onlineshop.integracion.jdbc;

import edu.co.sena.onlineshop.integracion.dao.*;
import edu.co.sena.onlineshop.integracion.factory.*;
import edu.co.sena.onlineshop.integracion.dto.*;
import edu.co.sena.onlineshop.integracion.exceptions.*;
import java.sql.Connection;
import java.util.Collection;
import org.apache.log4j.Logger;
import java.sql.PreparedStatement;
import java.sql.Statement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Time;
import java.util.List;
import java.util.Iterator;
import java.util.ArrayList;

public class CuentaDaoImpl extends AbstractDAO implements CuentaDao
{
	/** 
	 * The factory class for this DAO has two versions of the create() method - one that
takes no arguments and one that takes a Connection argument. If the Connection version
is chosen then the connection will be stored in this attribute and will be used by all
calls to this DAO, otherwise a new Connection will be allocated for each operation.
	 */
	protected java.sql.Connection userConn;

	protected static final Logger logger = Logger.getLogger( CuentaDaoImpl.class );

	/** 
	 * All finder methods in this class use this SELECT constant to build their queries
	 */
	protected final String SQL_SELECT = "SELECT PRIMER_NOMBRE, SEGUNDO_NOMBRE, PRIMER_APELLIDO, SEGUNDO_APELLIDO, TIPO_DOCUMENTO, NUMERO_DOCUMENTO, PASSWORD, CORREO_ELECTRONICO, USUARIO, usuario_idusuario FROM " + getTableName() + "";

	/** 
	 * Finder methods will pass this value to the JDBC setMaxRows method
	 */
	protected int maxRows;

	/** 
	 * SQL INSERT statement for this table
	 */
	protected final String SQL_INSERT = "INSERT INTO " + getTableName() + " ( PRIMER_NOMBRE, SEGUNDO_NOMBRE, PRIMER_APELLIDO, SEGUNDO_APELLIDO, TIPO_DOCUMENTO, NUMERO_DOCUMENTO, PASSWORD, CORREO_ELECTRONICO, USUARIO, usuario_idusuario ) VALUES ( ?, ?, ?, ?, ?, ?, ?, ?, ?, ? )";

	/** 
	 * SQL UPDATE statement for this table
	 */
	protected final String SQL_UPDATE = "UPDATE " + getTableName() + " SET PRIMER_NOMBRE = ?, SEGUNDO_NOMBRE = ?, PRIMER_APELLIDO = ?, SEGUNDO_APELLIDO = ?, TIPO_DOCUMENTO = ?, NUMERO_DOCUMENTO = ?, PASSWORD = ?, CORREO_ELECTRONICO = ?, USUARIO = ?, usuario_idusuario = ? WHERE NUMERO_DOCUMENTO = ? AND TIPO_DOCUMENTO = ?";

	/** 
	 * SQL DELETE statement for this table
	 */
	protected final String SQL_DELETE = "DELETE FROM " + getTableName() + " WHERE NUMERO_DOCUMENTO = ? AND TIPO_DOCUMENTO = ?";

	/** 
	 * Index of column PRIMER_NOMBRE
	 */
	protected static final int COLUMN_PRIMER_NOMBRE = 1;

	/** 
	 * Index of column SEGUNDO_NOMBRE
	 */
	protected static final int COLUMN_SEGUNDO_NOMBRE = 2;

	/** 
	 * Index of column PRIMER_APELLIDO
	 */
	protected static final int COLUMN_PRIMER_APELLIDO = 3;

	/** 
	 * Index of column SEGUNDO_APELLIDO
	 */
	protected static final int COLUMN_SEGUNDO_APELLIDO = 4;

	/** 
	 * Index of column TIPO_DOCUMENTO
	 */
	protected static final int COLUMN_TIPO_DOCUMENTO = 5;

	/** 
	 * Index of column NUMERO_DOCUMENTO
	 */
	protected static final int COLUMN_NUMERO_DOCUMENTO = 6;

	/** 
	 * Index of column PASSWORD
	 */
	protected static final int COLUMN_PASSWORD = 7;

	/** 
	 * Index of column CORREO_ELECTRONICO
	 */
	protected static final int COLUMN_CORREO_ELECTRONICO = 8;

	/** 
	 * Index of column USUARIO
	 */
	protected static final int COLUMN_USUARIO = 9;

	/** 
	 * Index of column usuario_idusuario
	 */
	protected static final int COLUMN_USUARIO_IDUSUARIO = 10;

	/** 
	 * Number of columns
	 */
	protected static final int NUMBER_OF_COLUMNS = 10;

	/** 
	 * Index of primary-key column NUMERO_DOCUMENTO
	 */
	protected static final int PK_COLUMN_NUMERO_DOCUMENTO = 1;

	/** 
	 * Index of primary-key column TIPO_DOCUMENTO
	 */
	protected static final int PK_COLUMN_TIPO_DOCUMENTO = 2;

	/** 
	 * Inserts a new row in the cuenta table.
	 */
	public CuentaPk insert(Cuenta dto) throws CuentaDaoException
	{
		long t1 = System.currentTimeMillis();
		// declare variables
		final boolean isConnSupplied = (userConn != null);
		Connection conn = null;
		PreparedStatement stmt = null;
		ResultSet rs = null;
		
		try {
			// get the user-specified connection or get a connection from the ResourceManager
			conn = isConnSupplied ? userConn : ResourceManager.getConnection();
		
			StringBuffer sql = new StringBuffer();
			StringBuffer values = new StringBuffer();
			sql.append( "INSERT INTO " + getTableName() + " (" );
			int modifiedCount = 0;
			if (dto.isPrimerNombreModified()) {
				if (modifiedCount>0) {
					sql.append( ", " );
					values.append( ", " );
				}
		
				sql.append( "PRIMER_NOMBRE" );
				values.append( "?" );
				modifiedCount++;
			}
		
			if (dto.isSegundoNombreModified()) {
				if (modifiedCount>0) {
					sql.append( ", " );
					values.append( ", " );
				}
		
				sql.append( "SEGUNDO_NOMBRE" );
				values.append( "?" );
				modifiedCount++;
			}
		
			if (dto.isPrimerApellidoModified()) {
				if (modifiedCount>0) {
					sql.append( ", " );
					values.append( ", " );
				}
		
				sql.append( "PRIMER_APELLIDO" );
				values.append( "?" );
				modifiedCount++;
			}
		
			if (dto.isSegundoApellidoModified()) {
				if (modifiedCount>0) {
					sql.append( ", " );
					values.append( ", " );
				}
		
				sql.append( "SEGUNDO_APELLIDO" );
				values.append( "?" );
				modifiedCount++;
			}
		
			if (dto.isTipoDocumentoModified()) {
				if (modifiedCount>0) {
					sql.append( ", " );
					values.append( ", " );
				}
		
				sql.append( "TIPO_DOCUMENTO" );
				values.append( "?" );
				modifiedCount++;
			}
		
			if (dto.isNumeroDocumentoModified()) {
				if (modifiedCount>0) {
					sql.append( ", " );
					values.append( ", " );
				}
		
				sql.append( "NUMERO_DOCUMENTO" );
				values.append( "?" );
				modifiedCount++;
			}
		
			if (dto.isPasswordModified()) {
				if (modifiedCount>0) {
					sql.append( ", " );
					values.append( ", " );
				}
		
				sql.append( "PASSWORD" );
				values.append( "?" );
				modifiedCount++;
			}
		
			if (dto.isCorreoElectronicoModified()) {
				if (modifiedCount>0) {
					sql.append( ", " );
					values.append( ", " );
				}
		
				sql.append( "CORREO_ELECTRONICO" );
				values.append( "?" );
				modifiedCount++;
			}
		
			if (dto.isUsuarioModified()) {
				if (modifiedCount>0) {
					sql.append( ", " );
					values.append( ", " );
				}
		
				sql.append( "USUARIO" );
				values.append( "?" );
				modifiedCount++;
			}
		
			if (dto.isUsuarioIdusuarioModified()) {
				if (modifiedCount>0) {
					sql.append( ", " );
					values.append( ", " );
				}
		
				sql.append( "usuario_idusuario" );
				values.append( "?" );
				modifiedCount++;
			}
		
			if (modifiedCount==0) {
				// nothing to insert
				throw new IllegalStateException( "Nothing to insert" );
			}
		
			sql.append( ") VALUES (" );
			sql.append( values );
			sql.append( ")" );
			stmt = conn.prepareStatement( sql.toString() );
			int index = 1;
			if (dto.isPrimerNombreModified()) {
				stmt.setString( index++, dto.getPrimerNombre() );
			}
		
			if (dto.isSegundoNombreModified()) {
				stmt.setString( index++, dto.getSegundoNombre() );
			}
		
			if (dto.isPrimerApellidoModified()) {
				stmt.setString( index++, dto.getPrimerApellido() );
			}
		
			if (dto.isSegundoApellidoModified()) {
				stmt.setString( index++, dto.getSegundoApellido() );
			}
		
			if (dto.isTipoDocumentoModified()) {
				stmt.setString( index++, dto.getTipoDocumento() );
			}
		
			if (dto.isNumeroDocumentoModified()) {
				stmt.setString( index++, dto.getNumeroDocumento() );
			}
		
			if (dto.isPasswordModified()) {
				stmt.setString( index++, dto.getPassword() );
			}
		
			if (dto.isCorreoElectronicoModified()) {
				stmt.setString( index++, dto.getCorreoElectronico() );
			}
		
			if (dto.isUsuarioModified()) {
				stmt.setString( index++, dto.getUsuario() );
			}
		
			if (dto.isUsuarioIdusuarioModified()) {
				stmt.setString( index++, dto.getUsuarioIdusuario() );
			}
		
			if (logger.isDebugEnabled()) {
				logger.debug( "Executing " + sql.toString() + " with values: " + dto);
			}
		
			int rows = stmt.executeUpdate();
			long t2 = System.currentTimeMillis();
			if (logger.isDebugEnabled()) {
				logger.debug( rows + " rows affected (" + (t2-t1) + " ms)");
			}
		
			reset(dto);
			return dto.createPk();
		}
		catch (Exception _e) {
			logger.error( "Exception: " + _e.getMessage(), _e );
			throw new CuentaDaoException( "Exception: " + _e.getMessage(), _e );
		}
		finally {
			ResourceManager.close(stmt);
			if (!isConnSupplied) {
				ResourceManager.close(conn);
			}
		
		}
		
	}

	/** 
	 * Updates a single row in the cuenta table.
	 */
	public void update(CuentaPk pk, Cuenta dto) throws CuentaDaoException
	{
		long t1 = System.currentTimeMillis();
		// declare variables
		final boolean isConnSupplied = (userConn != null);
		Connection conn = null;
		PreparedStatement stmt = null;
		
		try {
			// get the user-specified connection or get a connection from the ResourceManager
			conn = isConnSupplied ? userConn : ResourceManager.getConnection();
		
			StringBuffer sql = new StringBuffer();
			sql.append( "UPDATE " + getTableName() + " SET " );
			boolean modified = false;
			if (dto.isPrimerNombreModified()) {
				if (modified) {
					sql.append( ", " );
				}
		
				sql.append( "PRIMER_NOMBRE=?" );
				modified=true;
			}
		
			if (dto.isSegundoNombreModified()) {
				if (modified) {
					sql.append( ", " );
				}
		
				sql.append( "SEGUNDO_NOMBRE=?" );
				modified=true;
			}
		
			if (dto.isPrimerApellidoModified()) {
				if (modified) {
					sql.append( ", " );
				}
		
				sql.append( "PRIMER_APELLIDO=?" );
				modified=true;
			}
		
			if (dto.isSegundoApellidoModified()) {
				if (modified) {
					sql.append( ", " );
				}
		
				sql.append( "SEGUNDO_APELLIDO=?" );
				modified=true;
			}
		
			if (dto.isTipoDocumentoModified()) {
				if (modified) {
					sql.append( ", " );
				}
		
				sql.append( "TIPO_DOCUMENTO=?" );
				modified=true;
			}
		
			if (dto.isNumeroDocumentoModified()) {
				if (modified) {
					sql.append( ", " );
				}
		
				sql.append( "NUMERO_DOCUMENTO=?" );
				modified=true;
			}
		
			if (dto.isPasswordModified()) {
				if (modified) {
					sql.append( ", " );
				}
		
				sql.append( "PASSWORD=?" );
				modified=true;
			}
		
			if (dto.isCorreoElectronicoModified()) {
				if (modified) {
					sql.append( ", " );
				}
		
				sql.append( "CORREO_ELECTRONICO=?" );
				modified=true;
			}
		
			if (dto.isUsuarioModified()) {
				if (modified) {
					sql.append( ", " );
				}
		
				sql.append( "USUARIO=?" );
				modified=true;
			}
		
			if (dto.isUsuarioIdusuarioModified()) {
				if (modified) {
					sql.append( ", " );
				}
		
				sql.append( "usuario_idusuario=?" );
				modified=true;
			}
		
			if (!modified) {
				// nothing to update
				return;
			}
		
			sql.append( " WHERE NUMERO_DOCUMENTO=? AND TIPO_DOCUMENTO=?" );
			if (logger.isDebugEnabled()) {
				logger.debug( "Executing " + sql.toString() + " with values: " + dto);
			}
		
			stmt = conn.prepareStatement( sql.toString() );
			int index = 1;
			if (dto.isPrimerNombreModified()) {
				stmt.setString( index++, dto.getPrimerNombre() );
			}
		
			if (dto.isSegundoNombreModified()) {
				stmt.setString( index++, dto.getSegundoNombre() );
			}
		
			if (dto.isPrimerApellidoModified()) {
				stmt.setString( index++, dto.getPrimerApellido() );
			}
		
			if (dto.isSegundoApellidoModified()) {
				stmt.setString( index++, dto.getSegundoApellido() );
			}
		
			if (dto.isTipoDocumentoModified()) {
				stmt.setString( index++, dto.getTipoDocumento() );
			}
		
			if (dto.isNumeroDocumentoModified()) {
				stmt.setString( index++, dto.getNumeroDocumento() );
			}
		
			if (dto.isPasswordModified()) {
				stmt.setString( index++, dto.getPassword() );
			}
		
			if (dto.isCorreoElectronicoModified()) {
				stmt.setString( index++, dto.getCorreoElectronico() );
			}
		
			if (dto.isUsuarioModified()) {
				stmt.setString( index++, dto.getUsuario() );
			}
		
			if (dto.isUsuarioIdusuarioModified()) {
				stmt.setString( index++, dto.getUsuarioIdusuario() );
			}
		
			stmt.setString( index++, pk.getNumeroDocumento() );
			stmt.setString( index++, pk.getTipoDocumento() );
			int rows = stmt.executeUpdate();
			reset(dto);
			long t2 = System.currentTimeMillis();
			if (logger.isDebugEnabled()) {
				logger.debug( rows + " rows affected (" + (t2-t1) + " ms)");
			}
		
		}
		catch (Exception _e) {
			logger.error( "Exception: " + _e.getMessage(), _e );
			throw new CuentaDaoException( "Exception: " + _e.getMessage(), _e );
		}
		finally {
			ResourceManager.close(stmt);
			if (!isConnSupplied) {
				ResourceManager.close(conn);
			}
		
		}
		
	}

	/** 
	 * Deletes a single row in the cuenta table.
	 */
	public void delete(CuentaPk pk) throws CuentaDaoException
	{
		long t1 = System.currentTimeMillis();
		// declare variables
		final boolean isConnSupplied = (userConn != null);
		Connection conn = null;
		PreparedStatement stmt = null;
		
		try {
			// get the user-specified connection or get a connection from the ResourceManager
			conn = isConnSupplied ? userConn : ResourceManager.getConnection();
		
			if (logger.isDebugEnabled()) {
				logger.debug( "Executing " + SQL_DELETE + " with PK: " + pk);
			}
		
			stmt = conn.prepareStatement( SQL_DELETE );
			stmt.setString( 1, pk.getNumeroDocumento() );
			stmt.setString( 2, pk.getTipoDocumento() );
			int rows = stmt.executeUpdate();
			long t2 = System.currentTimeMillis();
			if (logger.isDebugEnabled()) {
				logger.debug( rows + " rows affected (" + (t2-t1) + " ms)");
			}
		
		}
		catch (Exception _e) {
			logger.error( "Exception: " + _e.getMessage(), _e );
			throw new CuentaDaoException( "Exception: " + _e.getMessage(), _e );
		}
		finally {
			ResourceManager.close(stmt);
			if (!isConnSupplied) {
				ResourceManager.close(conn);
			}
		
		}
		
	}

	/** 
	 * Returns the rows from the cuenta table that matches the specified primary-key value.
	 */
	public Cuenta findByPrimaryKey(CuentaPk pk) throws CuentaDaoException
	{
		return findByPrimaryKey( pk.getNumeroDocumento(), pk.getTipoDocumento() );
	}

	/** 
	 * Returns all rows from the cuenta table that match the criteria 'NUMERO_DOCUMENTO = :numeroDocumento AND TIPO_DOCUMENTO = :tipoDocumento'.
	 */
	public Cuenta findByPrimaryKey(String numeroDocumento, String tipoDocumento) throws CuentaDaoException
	{
		Cuenta ret[] = findByDynamicSelect( SQL_SELECT + " WHERE NUMERO_DOCUMENTO = ? AND TIPO_DOCUMENTO = ?", new Object[] { numeroDocumento, tipoDocumento } );
		return ret.length==0 ? null : ret[0];
	}

	/** 
	 * Returns all rows from the cuenta table that match the criteria ''.
	 */
	public Cuenta[] findAll() throws CuentaDaoException
	{
		return findByDynamicSelect( SQL_SELECT + " ORDER BY NUMERO_DOCUMENTO, TIPO_DOCUMENTO", null );
	}

	/** 
	 * Returns all rows from the cuenta table that match the criteria 'usuario_idusuario = :usuarioIdusuario'.
	 */
	public Cuenta[] findByUsuario(String usuarioIdusuario) throws CuentaDaoException
	{
		return findByDynamicSelect( SQL_SELECT + " WHERE usuario_idusuario = ?", new Object[] { usuarioIdusuario } );
	}

	/** 
	 * Returns all rows from the cuenta table that match the criteria 'PRIMER_NOMBRE = :primerNombre'.
	 */
	public Cuenta[] findWherePrimerNombreEquals(String primerNombre) throws CuentaDaoException
	{
		return findByDynamicSelect( SQL_SELECT + " WHERE PRIMER_NOMBRE = ? ORDER BY PRIMER_NOMBRE", new Object[] { primerNombre } );
	}

	/** 
	 * Returns all rows from the cuenta table that match the criteria 'SEGUNDO_NOMBRE = :segundoNombre'.
	 */
	public Cuenta[] findWhereSegundoNombreEquals(String segundoNombre) throws CuentaDaoException
	{
		return findByDynamicSelect( SQL_SELECT + " WHERE SEGUNDO_NOMBRE = ? ORDER BY SEGUNDO_NOMBRE", new Object[] { segundoNombre } );
	}

	/** 
	 * Returns all rows from the cuenta table that match the criteria 'PRIMER_APELLIDO = :primerApellido'.
	 */
	public Cuenta[] findWherePrimerApellidoEquals(String primerApellido) throws CuentaDaoException
	{
		return findByDynamicSelect( SQL_SELECT + " WHERE PRIMER_APELLIDO = ? ORDER BY PRIMER_APELLIDO", new Object[] { primerApellido } );
	}

	/** 
	 * Returns all rows from the cuenta table that match the criteria 'SEGUNDO_APELLIDO = :segundoApellido'.
	 */
	public Cuenta[] findWhereSegundoApellidoEquals(String segundoApellido) throws CuentaDaoException
	{
		return findByDynamicSelect( SQL_SELECT + " WHERE SEGUNDO_APELLIDO = ? ORDER BY SEGUNDO_APELLIDO", new Object[] { segundoApellido } );
	}

	/** 
	 * Returns all rows from the cuenta table that match the criteria 'TIPO_DOCUMENTO = :tipoDocumento'.
	 */
	public Cuenta[] findWhereTipoDocumentoEquals(String tipoDocumento) throws CuentaDaoException
	{
		return findByDynamicSelect( SQL_SELECT + " WHERE TIPO_DOCUMENTO = ? ORDER BY TIPO_DOCUMENTO", new Object[] { tipoDocumento } );
	}

	/** 
	 * Returns all rows from the cuenta table that match the criteria 'NUMERO_DOCUMENTO = :numeroDocumento'.
	 */
	public Cuenta[] findWhereNumeroDocumentoEquals(String numeroDocumento) throws CuentaDaoException
	{
		return findByDynamicSelect( SQL_SELECT + " WHERE NUMERO_DOCUMENTO = ? ORDER BY NUMERO_DOCUMENTO", new Object[] { numeroDocumento } );
	}

	/** 
	 * Returns all rows from the cuenta table that match the criteria 'PASSWORD = :password'.
	 */
	public Cuenta[] findWherePasswordEquals(String password) throws CuentaDaoException
	{
		return findByDynamicSelect( SQL_SELECT + " WHERE PASSWORD = ? ORDER BY PASSWORD", new Object[] { password } );
	}

	/** 
	 * Returns all rows from the cuenta table that match the criteria 'CORREO_ELECTRONICO = :correoElectronico'.
	 */
	public Cuenta[] findWhereCorreoElectronicoEquals(String correoElectronico) throws CuentaDaoException
	{
		return findByDynamicSelect( SQL_SELECT + " WHERE CORREO_ELECTRONICO = ? ORDER BY CORREO_ELECTRONICO", new Object[] { correoElectronico } );
	}

	/** 
	 * Returns all rows from the cuenta table that match the criteria 'USUARIO = :usuario'.
	 */
	public Cuenta[] findWhereUsuarioEquals(String usuario) throws CuentaDaoException
	{
		return findByDynamicSelect( SQL_SELECT + " WHERE USUARIO = ? ORDER BY USUARIO", new Object[] { usuario } );
	}

	/** 
	 * Returns all rows from the cuenta table that match the criteria 'usuario_idusuario = :usuarioIdusuario'.
	 */
	public Cuenta[] findWhereUsuarioIdusuarioEquals(String usuarioIdusuario) throws CuentaDaoException
	{
		return findByDynamicSelect( SQL_SELECT + " WHERE usuario_idusuario = ? ORDER BY usuario_idusuario", new Object[] { usuarioIdusuario } );
	}

	/**
	 * Method 'CuentaDaoImpl'
	 * 
	 */
	public CuentaDaoImpl()
	{
	}

	/**
	 * Method 'CuentaDaoImpl'
	 * 
	 * @param userConn
	 */
	public CuentaDaoImpl(final java.sql.Connection userConn)
	{
		this.userConn = userConn;
	}

	/** 
	 * Sets the value of maxRows
	 */
	public void setMaxRows(int maxRows)
	{
		this.maxRows = maxRows;
	}

	/** 
	 * Gets the value of maxRows
	 */
	public int getMaxRows()
	{
		return maxRows;
	}

	/**
	 * Method 'getTableName'
	 * 
	 * @return String
	 */
	public String getTableName()
	{
		return "onlineshop.cuenta";
	}

	/** 
	 * Fetches a single row from the result set
	 */
	protected Cuenta fetchSingleResult(ResultSet rs) throws SQLException
	{
		if (rs.next()) {
			Cuenta dto = new Cuenta();
			populateDto( dto, rs);
			return dto;
		} else {
			return null;
		}
		
	}

	/** 
	 * Fetches multiple rows from the result set
	 */
	protected Cuenta[] fetchMultiResults(ResultSet rs) throws SQLException
	{
		Collection resultList = new ArrayList();
		while (rs.next()) {
			Cuenta dto = new Cuenta();
			populateDto( dto, rs);
			resultList.add( dto );
		}
		
		Cuenta ret[] = new Cuenta[ resultList.size() ];
		resultList.toArray( ret );
		return ret;
	}

	/** 
	 * Populates a DTO with data from a ResultSet
	 */
	protected void populateDto(Cuenta dto, ResultSet rs) throws SQLException
	{
		dto.setPrimerNombre( rs.getString( COLUMN_PRIMER_NOMBRE ) );
		dto.setSegundoNombre( rs.getString( COLUMN_SEGUNDO_NOMBRE ) );
		dto.setPrimerApellido( rs.getString( COLUMN_PRIMER_APELLIDO ) );
		dto.setSegundoApellido( rs.getString( COLUMN_SEGUNDO_APELLIDO ) );
		dto.setTipoDocumento( rs.getString( COLUMN_TIPO_DOCUMENTO ) );
		dto.setNumeroDocumento( rs.getString( COLUMN_NUMERO_DOCUMENTO ) );
		dto.setPassword( rs.getString( COLUMN_PASSWORD ) );
		dto.setCorreoElectronico( rs.getString( COLUMN_CORREO_ELECTRONICO ) );
		dto.setUsuario( rs.getString( COLUMN_USUARIO ) );
		dto.setUsuarioIdusuario( rs.getString( COLUMN_USUARIO_IDUSUARIO ) );
		reset(dto);
	}

	/** 
	 * Resets the modified attributes in the DTO
	 */
	protected void reset(Cuenta dto)
	{
		dto.setPrimerNombreModified( false );
		dto.setSegundoNombreModified( false );
		dto.setPrimerApellidoModified( false );
		dto.setSegundoApellidoModified( false );
		dto.setTipoDocumentoModified( false );
		dto.setNumeroDocumentoModified( false );
		dto.setPasswordModified( false );
		dto.setCorreoElectronicoModified( false );
		dto.setUsuarioModified( false );
		dto.setUsuarioIdusuarioModified( false );
	}

	/** 
	 * Returns all rows from the cuenta table that match the specified arbitrary SQL statement
	 */
	public Cuenta[] findByDynamicSelect(String sql, Object[] sqlParams) throws CuentaDaoException
	{
		// declare variables
		final boolean isConnSupplied = (userConn != null);
		Connection conn = null;
		PreparedStatement stmt = null;
		ResultSet rs = null;
		
		try {
			// get the user-specified connection or get a connection from the ResourceManager
			conn = isConnSupplied ? userConn : ResourceManager.getConnection();
		
			// construct the SQL statement
			final String SQL = sql;
		
		
			if (logger.isDebugEnabled()) {
				logger.debug( "Executing " + SQL);
			}
		
			// prepare statement
			stmt = conn.prepareStatement( SQL );
			stmt.setMaxRows( maxRows );
		
			// bind parameters
			for (int i=0; sqlParams!=null && i<sqlParams.length; i++ ) {
				stmt.setObject( i+1, sqlParams[i] );
			}
		
		
			rs = stmt.executeQuery();
		
			// fetch the results
			return fetchMultiResults(rs);
		}
		catch (Exception _e) {
			logger.error( "Exception: " + _e.getMessage(), _e );
			throw new CuentaDaoException( "Exception: " + _e.getMessage(), _e );
		}
		finally {
			ResourceManager.close(rs);
			ResourceManager.close(stmt);
			if (!isConnSupplied) {
				ResourceManager.close(conn);
			}
		
		}
		
	}

	/** 
	 * Returns all rows from the cuenta table that match the specified arbitrary SQL statement
	 */
	public Cuenta[] findByDynamicWhere(String sql, Object[] sqlParams) throws CuentaDaoException
	{
		// declare variables
		final boolean isConnSupplied = (userConn != null);
		Connection conn = null;
		PreparedStatement stmt = null;
		ResultSet rs = null;
		
		try {
			// get the user-specified connection or get a connection from the ResourceManager
			conn = isConnSupplied ? userConn : ResourceManager.getConnection();
		
			// construct the SQL statement
			final String SQL = SQL_SELECT + " WHERE " + sql;
		
		
			if (logger.isDebugEnabled()) {
				logger.debug( "Executing " + SQL);
			}
		
			// prepare statement
			stmt = conn.prepareStatement( SQL );
			stmt.setMaxRows( maxRows );
		
			// bind parameters
			for (int i=0; sqlParams!=null && i<sqlParams.length; i++ ) {
				stmt.setObject( i+1, sqlParams[i] );
			}
		
		
			rs = stmt.executeQuery();
		
			// fetch the results
			return fetchMultiResults(rs);
		}
		catch (Exception _e) {
			logger.error( "Exception: " + _e.getMessage(), _e );
			throw new CuentaDaoException( "Exception: " + _e.getMessage(), _e );
		}
		finally {
			ResourceManager.close(rs);
			ResourceManager.close(stmt);
			if (!isConnSupplied) {
				ResourceManager.close(conn);
			}
		
		}
		
	}

}
