/*
 * This source file was generated by FireStorm/DAO.
 * 
 * If you purchase a full license for FireStorm/DAO you can customize this header file.
 * 
 * For more information please visit http://www.codefutures.com/products/firestorm
 */

package edu.co.sena.onlineshop.negocio.examples;

import java.math.*;
import java.util.Date;
import java.util.Collection;
import edu.co.sena.onlineshop.integracion.dao.DomicilioProveeDao;
import edu.co.sena.onlineshop.integracion.dto.DomicilioProvee;
import edu.co.sena.onlineshop.integracion.exceptions.DomicilioProveeDaoException;
import edu.co.sena.onlineshop.integracion.factory.DomicilioProveeDaoFactory;

public class DomicilioProveeDaoSample
{
	/**
	 * Method 'main'
	 * 
	 * @param arg
	 * @throws Exception
	 */
	public static void main(String[] arg) throws Exception
	{
		// Uncomment one of the lines below to test the generated code
		
		// findAll();
		// findByMunicipio(0);
		// findByProveedor("", "");
		// findWhereDireccionEquals("");
		// findWhereTelefonoEquals("");
		// findWhereBarrioEquals("");
		// findWhereLocalidadEquals("");
		// findWhereCorreoPostalEquals("");
		// findWhereMunicipioIdmunicipioEquals(0);
		// findWhereProveedorTipoDocumentoEquals("");
		// findWhereProveedorNumDocumentoEquals("");
	}

	/**
	 * Method 'findAll'
	 * 
	 */
	public static void findAll()
	{
		try {
			DomicilioProveeDao _dao = getDomicilioProveeDao();
			DomicilioProvee _result[] = _dao.findAll();
			for (int i=0; i<_result.length; i++ ) {
				display( _result[i] );
			}
		
		}
		catch (Exception _e) {
			_e.printStackTrace();
		}
		
	}

	/**
	 * Method 'findByMunicipio'
	 * 
	 * @param municipioIdmunicipio
	 */
	public static void findByMunicipio(int municipioIdmunicipio)
	{
		try {
			DomicilioProveeDao _dao = getDomicilioProveeDao();
			DomicilioProvee _result[] = _dao.findByMunicipio(municipioIdmunicipio);
			for (int i=0; i<_result.length; i++ ) {
				display( _result[i] );
			}
		
		}
		catch (Exception _e) {
			_e.printStackTrace();
		}
		
	}

	/**
	 * Method 'findByProveedor'
	 * 
	 * @param proveedorTipoDocumento
	 * @param proveedorNumDocumento
	 */
	public static void findByProveedor(String proveedorTipoDocumento, String proveedorNumDocumento)
	{
		try {
			DomicilioProveeDao _dao = getDomicilioProveeDao();
			DomicilioProvee _result[] = _dao.findByProveedor(proveedorTipoDocumento, proveedorNumDocumento);
			for (int i=0; i<_result.length; i++ ) {
				display( _result[i] );
			}
		
		}
		catch (Exception _e) {
			_e.printStackTrace();
		}
		
	}

	/**
	 * Method 'findWhereDireccionEquals'
	 * 
	 * @param direccion
	 */
	public static void findWhereDireccionEquals(String direccion)
	{
		try {
			DomicilioProveeDao _dao = getDomicilioProveeDao();
			DomicilioProvee _result[] = _dao.findWhereDireccionEquals(direccion);
			for (int i=0; i<_result.length; i++ ) {
				display( _result[i] );
			}
		
		}
		catch (Exception _e) {
			_e.printStackTrace();
		}
		
	}

	/**
	 * Method 'findWhereTelefonoEquals'
	 * 
	 * @param telefono
	 */
	public static void findWhereTelefonoEquals(String telefono)
	{
		try {
			DomicilioProveeDao _dao = getDomicilioProveeDao();
			DomicilioProvee _result[] = _dao.findWhereTelefonoEquals(telefono);
			for (int i=0; i<_result.length; i++ ) {
				display( _result[i] );
			}
		
		}
		catch (Exception _e) {
			_e.printStackTrace();
		}
		
	}

	/**
	 * Method 'findWhereBarrioEquals'
	 * 
	 * @param barrio
	 */
	public static void findWhereBarrioEquals(String barrio)
	{
		try {
			DomicilioProveeDao _dao = getDomicilioProveeDao();
			DomicilioProvee _result[] = _dao.findWhereBarrioEquals(barrio);
			for (int i=0; i<_result.length; i++ ) {
				display( _result[i] );
			}
		
		}
		catch (Exception _e) {
			_e.printStackTrace();
		}
		
	}

	/**
	 * Method 'findWhereLocalidadEquals'
	 * 
	 * @param localidad
	 */
	public static void findWhereLocalidadEquals(String localidad)
	{
		try {
			DomicilioProveeDao _dao = getDomicilioProveeDao();
			DomicilioProvee _result[] = _dao.findWhereLocalidadEquals(localidad);
			for (int i=0; i<_result.length; i++ ) {
				display( _result[i] );
			}
		
		}
		catch (Exception _e) {
			_e.printStackTrace();
		}
		
	}

	/**
	 * Method 'findWhereCorreoPostalEquals'
	 * 
	 * @param correoPostal
	 */
	public static void findWhereCorreoPostalEquals(String correoPostal)
	{
		try {
			DomicilioProveeDao _dao = getDomicilioProveeDao();
			DomicilioProvee _result[] = _dao.findWhereCorreoPostalEquals(correoPostal);
			for (int i=0; i<_result.length; i++ ) {
				display( _result[i] );
			}
		
		}
		catch (Exception _e) {
			_e.printStackTrace();
		}
		
	}

	/**
	 * Method 'findWhereMunicipioIdmunicipioEquals'
	 * 
	 * @param municipioIdmunicipio
	 */
	public static void findWhereMunicipioIdmunicipioEquals(int municipioIdmunicipio)
	{
		try {
			DomicilioProveeDao _dao = getDomicilioProveeDao();
			DomicilioProvee _result[] = _dao.findWhereMunicipioIdmunicipioEquals(municipioIdmunicipio);
			for (int i=0; i<_result.length; i++ ) {
				display( _result[i] );
			}
		
		}
		catch (Exception _e) {
			_e.printStackTrace();
		}
		
	}

	/**
	 * Method 'findWhereProveedorTipoDocumentoEquals'
	 * 
	 * @param proveedorTipoDocumento
	 */
	public static void findWhereProveedorTipoDocumentoEquals(String proveedorTipoDocumento)
	{
		try {
			DomicilioProveeDao _dao = getDomicilioProveeDao();
			DomicilioProvee _result[] = _dao.findWhereProveedorTipoDocumentoEquals(proveedorTipoDocumento);
			for (int i=0; i<_result.length; i++ ) {
				display( _result[i] );
			}
		
		}
		catch (Exception _e) {
			_e.printStackTrace();
		}
		
	}

	/**
	 * Method 'findWhereProveedorNumDocumentoEquals'
	 * 
	 * @param proveedorNumDocumento
	 */
	public static void findWhereProveedorNumDocumentoEquals(String proveedorNumDocumento)
	{
		try {
			DomicilioProveeDao _dao = getDomicilioProveeDao();
			DomicilioProvee _result[] = _dao.findWhereProveedorNumDocumentoEquals(proveedorNumDocumento);
			for (int i=0; i<_result.length; i++ ) {
				display( _result[i] );
			}
		
		}
		catch (Exception _e) {
			_e.printStackTrace();
		}
		
	}

	/**
	 * Method 'getDomicilioProveeDao'
	 * 
	 * @return DomicilioProveeDao
	 */
	public static DomicilioProveeDao getDomicilioProveeDao()
	{
		return DomicilioProveeDaoFactory.create();
	}

	/**
	 * Method 'display'
	 * 
	 * @param dto
	 */
	public static void display(DomicilioProvee dto)
	{
		StringBuffer buf = new StringBuffer();
		buf.append( dto.getDireccion() );
		buf.append( ", " );
		buf.append( dto.getTelefono() );
		buf.append( ", " );
		buf.append( dto.getBarrio() );
		buf.append( ", " );
		buf.append( dto.getLocalidad() );
		buf.append( ", " );
		buf.append( dto.getCorreoPostal() );
		buf.append( ", " );
		buf.append( dto.getMunicipioIdmunicipio() );
		buf.append( ", " );
		buf.append( dto.getProveedorTipoDocumento() );
		buf.append( ", " );
		buf.append( dto.getProveedorNumDocumento() );
		System.out.println( buf.toString() );
	}

}
