/*
 * This source file was generated by FireStorm/DAO.
 * 
 * If you purchase a full license for FireStorm/DAO you can customize this header file.
 * 
 * For more information please visit http://www.codefutures.com/products/firestorm
 */

package edu.co.sena.onlineshop.integracion.dao;

import edu.co.sena.onlineshop.integracion.dto.*;
import edu.co.sena.onlineshop.integracion.exceptions.*;

public interface DomicilioCuentasDao
{
	/** 
	 * Inserts a new row in the domicilio_cuentas table.
	 */
	public DomicilioCuentasPk insert(DomicilioCuentas dto) throws DomicilioCuentasDaoException;

	/** 
	 * Updates a single row in the domicilio_cuentas table.
	 */
	public void update(DomicilioCuentasPk pk, DomicilioCuentas dto) throws DomicilioCuentasDaoException;

	/** 
	 * Deletes a single row in the domicilio_cuentas table.
	 */
	public void delete(DomicilioCuentasPk pk) throws DomicilioCuentasDaoException;

	/** 
	 * Returns the rows from the domicilio_cuentas table that matches the specified primary-key value.
	 */
	public DomicilioCuentas findByPrimaryKey(DomicilioCuentasPk pk) throws DomicilioCuentasDaoException;

	/** 
	 * Returns all rows from the domicilio_cuentas table that match the criteria 'CUENTA_NUMERO_DOCUMENTO = :cuentaNumeroDocumento AND CUENTA_TIPO_DOCUMENTO = :cuentaTipoDocumento'.
	 */
	public DomicilioCuentas findByPrimaryKey(String cuentaNumeroDocumento, String cuentaTipoDocumento) throws DomicilioCuentasDaoException;

	/** 
	 * Returns all rows from the domicilio_cuentas table that match the criteria ''.
	 */
	public DomicilioCuentas[] findAll() throws DomicilioCuentasDaoException;

	/** 
	 * Returns all rows from the domicilio_cuentas table that match the criteria 'MUNICIPIO_idMUNICIPIO = :municipioIdmunicipio'.
	 */
	public DomicilioCuentas[] findByMunicipio(int municipioIdmunicipio) throws DomicilioCuentasDaoException;

	/** 
	 * Returns all rows from the domicilio_cuentas table that match the criteria 'CUENTA_NUMERO_DOCUMENTO = :cuentaNumeroDocumento AND CUENTA_TIPO_DOCUMENTO = :cuentaTipoDocumento'.
	 */
	public DomicilioCuentas[] findByCuenta(String cuentaNumeroDocumento, String cuentaTipoDocumento) throws DomicilioCuentasDaoException;

	/** 
	 * Returns all rows from the domicilio_cuentas table that match the criteria 'direccion = :direccion'.
	 */
	public DomicilioCuentas[] findWhereDireccionEquals(String direccion) throws DomicilioCuentasDaoException;

	/** 
	 * Returns all rows from the domicilio_cuentas table that match the criteria 'telefono = :telefono'.
	 */
	public DomicilioCuentas[] findWhereTelefonoEquals(String telefono) throws DomicilioCuentasDaoException;

	/** 
	 * Returns all rows from the domicilio_cuentas table that match the criteria 'barrio = :barrio'.
	 */
	public DomicilioCuentas[] findWhereBarrioEquals(String barrio) throws DomicilioCuentasDaoException;

	/** 
	 * Returns all rows from the domicilio_cuentas table that match the criteria 'localidad = :localidad'.
	 */
	public DomicilioCuentas[] findWhereLocalidadEquals(String localidad) throws DomicilioCuentasDaoException;

	/** 
	 * Returns all rows from the domicilio_cuentas table that match the criteria 'CORREO_POSTAL = :correoPostal'.
	 */
	public DomicilioCuentas[] findWhereCorreoPostalEquals(String correoPostal) throws DomicilioCuentasDaoException;

	/** 
	 * Returns all rows from the domicilio_cuentas table that match the criteria 'MUNICIPIO_idMUNICIPIO = :municipioIdmunicipio'.
	 */
	public DomicilioCuentas[] findWhereMunicipioIdmunicipioEquals(int municipioIdmunicipio) throws DomicilioCuentasDaoException;

	/** 
	 * Returns all rows from the domicilio_cuentas table that match the criteria 'CUENTA_NUMERO_DOCUMENTO = :cuentaNumeroDocumento'.
	 */
	public DomicilioCuentas[] findWhereCuentaNumeroDocumentoEquals(String cuentaNumeroDocumento) throws DomicilioCuentasDaoException;

	/** 
	 * Returns all rows from the domicilio_cuentas table that match the criteria 'CUENTA_TIPO_DOCUMENTO = :cuentaTipoDocumento'.
	 */
	public DomicilioCuentas[] findWhereCuentaTipoDocumentoEquals(String cuentaTipoDocumento) throws DomicilioCuentasDaoException;

	/** 
	 * Sets the value of maxRows
	 */
	public void setMaxRows(int maxRows);

	/** 
	 * Gets the value of maxRows
	 */
	public int getMaxRows();

	/** 
	 * Returns all rows from the domicilio_cuentas table that match the specified arbitrary SQL statement
	 */
	public DomicilioCuentas[] findByDynamicSelect(String sql, Object[] sqlParams) throws DomicilioCuentasDaoException;

	/** 
	 * Returns all rows from the domicilio_cuentas table that match the specified arbitrary SQL statement
	 */
	public DomicilioCuentas[] findByDynamicWhere(String sql, Object[] sqlParams) throws DomicilioCuentasDaoException;

}
