/*
 * This source file was generated by FireStorm/DAO.
 * 
 * If you purchase a full license for FireStorm/DAO you can customize this header file.
 * 
 * For more information please visit http://www.codefutures.com/products/firestorm
 */

package edu.co.sena.onlineshop.integracion.dao;

import edu.co.sena.onlineshop.integracion.dto.*;
import edu.co.sena.onlineshop.integracion.exceptions.*;

public interface ProveedorDao
{
	/** 
	 * Inserts a new row in the proveedor table.
	 */
	public ProveedorPk insert(Proveedor dto) throws ProveedorDaoException;

	/** 
	 * Updates a single row in the proveedor table.
	 */
	public void update(ProveedorPk pk, Proveedor dto) throws ProveedorDaoException;

	/** 
	 * Deletes a single row in the proveedor table.
	 */
	public void delete(ProveedorPk pk) throws ProveedorDaoException;

	/** 
	 * Returns the rows from the proveedor table that matches the specified primary-key value.
	 */
	public Proveedor findByPrimaryKey(ProveedorPk pk) throws ProveedorDaoException;

	/** 
	 * Returns all rows from the proveedor table that match the criteria 'TIPO_DOCUMENTO = :tipoDocumento AND NUM_DOCUMENTO = :numDocumento'.
	 */
	public Proveedor findByPrimaryKey(String tipoDocumento, String numDocumento) throws ProveedorDaoException;

	/** 
	 * Returns all rows from the proveedor table that match the criteria ''.
	 */
	public Proveedor[] findAll() throws ProveedorDaoException;

	/** 
	 * Returns all rows from the proveedor table that match the criteria 'TIPO_DOCUMENTO = :tipoDocumento'.
	 */
	public Proveedor[] findWhereTipoDocumentoEquals(String tipoDocumento) throws ProveedorDaoException;

	/** 
	 * Returns all rows from the proveedor table that match the criteria 'NUM_DOCUMENTO = :numDocumento'.
	 */
	public Proveedor[] findWhereNumDocumentoEquals(String numDocumento) throws ProveedorDaoException;

	/** 
	 * Returns all rows from the proveedor table that match the criteria 'NOMBRE_PROVEEDOR = :nombreProveedor'.
	 */
	public Proveedor[] findWhereNombreProveedorEquals(String nombreProveedor) throws ProveedorDaoException;

	/** 
	 * Returns all rows from the proveedor table that match the criteria 'TELEFONO = :telefono'.
	 */
	public Proveedor[] findWhereTelefonoEquals(String telefono) throws ProveedorDaoException;

	/** 
	 * Returns all rows from the proveedor table that match the criteria 'DIRECCION = :direccion'.
	 */
	public Proveedor[] findWhereDireccionEquals(String direccion) throws ProveedorDaoException;

	/** 
	 * Returns all rows from the proveedor table that match the criteria 'CORREO = :correo'.
	 */
	public Proveedor[] findWhereCorreoEquals(String correo) throws ProveedorDaoException;

	/** 
	 * Returns all rows from the proveedor table that match the criteria 'domicilio_iddomicilio = :domicilioIddomicilio'.
	 */
	public Proveedor[] findWhereDomicilioIddomicilioEquals(int domicilioIddomicilio) throws ProveedorDaoException;

	/** 
	 * Sets the value of maxRows
	 */
	public void setMaxRows(int maxRows);

	/** 
	 * Gets the value of maxRows
	 */
	public int getMaxRows();

	/** 
	 * Returns all rows from the proveedor table that match the specified arbitrary SQL statement
	 */
	public Proveedor[] findByDynamicSelect(String sql, Object[] sqlParams) throws ProveedorDaoException;

	/** 
	 * Returns all rows from the proveedor table that match the specified arbitrary SQL statement
	 */
	public Proveedor[] findByDynamicWhere(String sql, Object[] sqlParams) throws ProveedorDaoException;

}
