/*
 * This source file was generated by FireStorm/DAO.
 * 
 * If you purchase a full license for FireStorm/DAO you can customize this header file.
 * 
 * For more information please visit http://www.codefutures.com/products/firestorm
 */

package edu.co.sena.onlineshop.negocio.example2;

import edu.co.sena.onlineshop.negocio.example.*;
import java.math.*;
import java.util.Date;
import java.util.Collection;
import edu.co.sena.onlineshop.integracion.dao.DomicilioCuentasDao;
import edu.co.sena.onlineshop.integracion.dto.DomicilioCuentas;
import edu.co.sena.onlineshop.integracion.exceptions.DomicilioCuentasDaoException;
import edu.co.sena.onlineshop.integracion.factory.DomicilioCuentasDaoFactory;

public class DomicilioCuentasDaoSample
{
	/**
	 * Method 'main'
	 * 
	 * @param arg
	 * @throws Exception
	 */
	public static void main(String[] arg) throws Exception
	{
		// Uncomment one of the lines below to test the generated code
		
		// findAll();
		// findByMunicipio(0);
		// findByCuenta("", "");
		// findWhereDireccionEquals("");
		// findWhereTelefonoEquals("");
		// findWhereBarrioEquals("");
		// findWhereLocalidadEquals("");
		// findWhereCorreoPostalEquals("");
		// findWhereMunicipioIdmunicipioEquals(0);
		// findWhereCuentaNumeroDocumentoEquals("");
		// findWhereCuentaTipoDocumentoEquals("");
	}

	/**
	 * Method 'findAll'
	 * 
	 */
	public static void findAll()
	{
		try {
			DomicilioCuentasDao _dao = getDomicilioCuentasDao();
			DomicilioCuentas _result[] = _dao.findAll();
			for (int i=0; i<_result.length; i++ ) {
				display( _result[i] );
			}
		
		}
		catch (Exception _e) {
			_e.printStackTrace();
		}
		
	}

	/**
	 * Method 'findByMunicipio'
	 * 
	 * @param municipioIdmunicipio
	 */
	public static void findByMunicipio(int municipioIdmunicipio)
	{
		try {
			DomicilioCuentasDao _dao = getDomicilioCuentasDao();
			DomicilioCuentas _result[] = _dao.findByMunicipio(municipioIdmunicipio);
			for (int i=0; i<_result.length; i++ ) {
				display( _result[i] );
			}
		
		}
		catch (Exception _e) {
			_e.printStackTrace();
		}
		
	}

	/**
	 * Method 'findByCuenta'
	 * 
	 * @param cuentaNumeroDocumento
	 * @param cuentaTipoDocumento
	 */
	public static void findByCuenta(String cuentaNumeroDocumento, String cuentaTipoDocumento)
	{
		try {
			DomicilioCuentasDao _dao = getDomicilioCuentasDao();
			DomicilioCuentas _result[] = _dao.findByCuenta(cuentaNumeroDocumento, cuentaTipoDocumento);
			for (int i=0; i<_result.length; i++ ) {
				display( _result[i] );
			}
		
		}
		catch (Exception _e) {
			_e.printStackTrace();
		}
		
	}

	/**
	 * Method 'findWhereDireccionEquals'
	 * 
	 * @param direccion
	 */
	public static void findWhereDireccionEquals(String direccion)
	{
		try {
			DomicilioCuentasDao _dao = getDomicilioCuentasDao();
			DomicilioCuentas _result[] = _dao.findWhereDireccionEquals(direccion);
			for (int i=0; i<_result.length; i++ ) {
				display( _result[i] );
			}
		
		}
		catch (Exception _e) {
			_e.printStackTrace();
		}
		
	}

	/**
	 * Method 'findWhereTelefonoEquals'
	 * 
	 * @param telefono
	 */
	public static void findWhereTelefonoEquals(String telefono)
	{
		try {
			DomicilioCuentasDao _dao = getDomicilioCuentasDao();
			DomicilioCuentas _result[] = _dao.findWhereTelefonoEquals(telefono);
			for (int i=0; i<_result.length; i++ ) {
				display( _result[i] );
			}
		
		}
		catch (Exception _e) {
			_e.printStackTrace();
		}
		
	}

	/**
	 * Method 'findWhereBarrioEquals'
	 * 
	 * @param barrio
	 */
	public static void findWhereBarrioEquals(String barrio)
	{
		try {
			DomicilioCuentasDao _dao = getDomicilioCuentasDao();
			DomicilioCuentas _result[] = _dao.findWhereBarrioEquals(barrio);
			for (int i=0; i<_result.length; i++ ) {
				display( _result[i] );
			}
		
		}
		catch (Exception _e) {
			_e.printStackTrace();
		}
		
	}

	/**
	 * Method 'findWhereLocalidadEquals'
	 * 
	 * @param localidad
	 */
	public static void findWhereLocalidadEquals(String localidad)
	{
		try {
			DomicilioCuentasDao _dao = getDomicilioCuentasDao();
			DomicilioCuentas _result[] = _dao.findWhereLocalidadEquals(localidad);
			for (int i=0; i<_result.length; i++ ) {
				display( _result[i] );
			}
		
		}
		catch (Exception _e) {
			_e.printStackTrace();
		}
		
	}

	/**
	 * Method 'findWhereCorreoPostalEquals'
	 * 
	 * @param correoPostal
	 */
	public static void findWhereCorreoPostalEquals(String correoPostal)
	{
		try {
			DomicilioCuentasDao _dao = getDomicilioCuentasDao();
			DomicilioCuentas _result[] = _dao.findWhereCorreoPostalEquals(correoPostal);
			for (int i=0; i<_result.length; i++ ) {
				display( _result[i] );
			}
		
		}
		catch (Exception _e) {
			_e.printStackTrace();
		}
		
	}

	/**
	 * Method 'findWhereMunicipioIdmunicipioEquals'
	 * 
	 * @param municipioIdmunicipio
	 */
	public static void findWhereMunicipioIdmunicipioEquals(int municipioIdmunicipio)
	{
		try {
			DomicilioCuentasDao _dao = getDomicilioCuentasDao();
			DomicilioCuentas _result[] = _dao.findWhereMunicipioIdmunicipioEquals(municipioIdmunicipio);
			for (int i=0; i<_result.length; i++ ) {
				display( _result[i] );
			}
		
		}
		catch (Exception _e) {
			_e.printStackTrace();
		}
		
	}

	/**
	 * Method 'findWhereCuentaNumeroDocumentoEquals'
	 * 
	 * @param cuentaNumeroDocumento
	 */
	public static void findWhereCuentaNumeroDocumentoEquals(String cuentaNumeroDocumento)
	{
		try {
			DomicilioCuentasDao _dao = getDomicilioCuentasDao();
			DomicilioCuentas _result[] = _dao.findWhereCuentaNumeroDocumentoEquals(cuentaNumeroDocumento);
			for (int i=0; i<_result.length; i++ ) {
				display( _result[i] );
			}
		
		}
		catch (Exception _e) {
			_e.printStackTrace();
		}
		
	}

	/**
	 * Method 'findWhereCuentaTipoDocumentoEquals'
	 * 
	 * @param cuentaTipoDocumento
	 */
	public static void findWhereCuentaTipoDocumentoEquals(String cuentaTipoDocumento)
	{
		try {
			DomicilioCuentasDao _dao = getDomicilioCuentasDao();
			DomicilioCuentas _result[] = _dao.findWhereCuentaTipoDocumentoEquals(cuentaTipoDocumento);
			for (int i=0; i<_result.length; i++ ) {
				display( _result[i] );
			}
		
		}
		catch (Exception _e) {
			_e.printStackTrace();
		}
		
	}

	/**
	 * Method 'getDomicilioCuentasDao'
	 * 
	 * @return DomicilioCuentasDao
	 */
	public static DomicilioCuentasDao getDomicilioCuentasDao()
	{
		return DomicilioCuentasDaoFactory.create();
	}

	/**
	 * Method 'display'
	 * 
	 * @param dto
	 */
	public static void display(DomicilioCuentas dto)
	{
		StringBuffer buf = new StringBuffer();
		buf.append( dto.getDireccion() );
		buf.append( ", " );
		buf.append( dto.getTelefono() );
		buf.append( ", " );
		buf.append( dto.getBarrio() );
		buf.append( ", " );
		buf.append( dto.getLocalidad() );
		buf.append( ", " );
		buf.append( dto.getCorreoPostal() );
		buf.append( ", " );
		buf.append( dto.getMunicipioIdmunicipio() );
		buf.append( ", " );
		buf.append( dto.getCuentaNumeroDocumento() );
		buf.append( ", " );
		buf.append( dto.getCuentaTipoDocumento() );
		System.out.println( buf.toString() );
	}

}
