/*
 * This source file was generated by FireStorm/DAO.
 * 
 * If you purchase a full license for FireStorm/DAO you can customize this header file.
 * 
 * For more information please visit http://www.codefutures.com/products/firestorm
 */

package edu.co.sena.onlineshop.integracion.jdbc;

import edu.co.sena.onlineshop.integracion.dao.*;
import edu.co.sena.onlineshop.integracion.factory.*;
import edu.co.sena.onlineshop.integracion.dto.*;
import edu.co.sena.onlineshop.integracion.exceptions.*;
import java.sql.Connection;
import java.util.Collection;
import java.sql.PreparedStatement;
import java.sql.Statement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Time;
import java.util.List;
import java.util.Iterator;
import java.util.ArrayList;

public class InventarioComprasDaoImpl extends AbstractDAO implements InventarioComprasDao
{
	/** 
	 * The factory class for this DAO has two versions of the create() method - one that
takes no arguments and one that takes a Connection argument. If the Connection version
is chosen then the connection will be stored in this attribute and will be used by all
calls to this DAO, otherwise a new Connection will be allocated for each operation.
	 */
	protected java.sql.Connection userConn;

	/** 
	 * All finder methods in this class use this SELECT constant to build their queries
	 */
	protected final String SQL_SELECT = "SELECT ID_INVENTARIO, PRODUCTO_ID_PRODUCTO, CAN_PRO_COMPRADO, FECHA_COMPRA, PROVEEDOR_TIPO_DOCUMENTO, PROVEEDOR_NUM_DOCUMENTO FROM " + getTableName() + "";

	/** 
	 * Finder methods will pass this value to the JDBC setMaxRows method
	 */
	protected int maxRows;

	/** 
	 * SQL INSERT statement for this table
	 */
	protected final String SQL_INSERT = "INSERT INTO " + getTableName() + " ( ID_INVENTARIO, PRODUCTO_ID_PRODUCTO, CAN_PRO_COMPRADO, FECHA_COMPRA, PROVEEDOR_TIPO_DOCUMENTO, PROVEEDOR_NUM_DOCUMENTO ) VALUES ( ?, ?, ?, ?, ?, ? )";

	/** 
	 * SQL UPDATE statement for this table
	 */
	protected final String SQL_UPDATE = "UPDATE " + getTableName() + " SET ID_INVENTARIO = ?, PRODUCTO_ID_PRODUCTO = ?, CAN_PRO_COMPRADO = ?, FECHA_COMPRA = ?, PROVEEDOR_TIPO_DOCUMENTO = ?, PROVEEDOR_NUM_DOCUMENTO = ? WHERE ID_INVENTARIO = ? AND PRODUCTO_ID_PRODUCTO = ? AND PROVEEDOR_TIPO_DOCUMENTO = ? AND PROVEEDOR_NUM_DOCUMENTO = ?";

	/** 
	 * SQL DELETE statement for this table
	 */
	protected final String SQL_DELETE = "DELETE FROM " + getTableName() + " WHERE ID_INVENTARIO = ? AND PRODUCTO_ID_PRODUCTO = ? AND PROVEEDOR_TIPO_DOCUMENTO = ? AND PROVEEDOR_NUM_DOCUMENTO = ?";

	/** 
	 * Index of column ID_INVENTARIO
	 */
	protected static final int COLUMN_ID_INVENTARIO = 1;

	/** 
	 * Index of column PRODUCTO_ID_PRODUCTO
	 */
	protected static final int COLUMN_PRODUCTO_ID_PRODUCTO = 2;

	/** 
	 * Index of column CAN_PRO_COMPRADO
	 */
	protected static final int COLUMN_CAN_PRO_COMPRADO = 3;

	/** 
	 * Index of column FECHA_COMPRA
	 */
	protected static final int COLUMN_FECHA_COMPRA = 4;

	/** 
	 * Index of column PROVEEDOR_TIPO_DOCUMENTO
	 */
	protected static final int COLUMN_PROVEEDOR_TIPO_DOCUMENTO = 5;

	/** 
	 * Index of column PROVEEDOR_NUM_DOCUMENTO
	 */
	protected static final int COLUMN_PROVEEDOR_NUM_DOCUMENTO = 6;

	/** 
	 * Number of columns
	 */
	protected static final int NUMBER_OF_COLUMNS = 6;

	/** 
	 * Index of primary-key column ID_INVENTARIO
	 */
	protected static final int PK_COLUMN_ID_INVENTARIO = 1;

	/** 
	 * Index of primary-key column PRODUCTO_ID_PRODUCTO
	 */
	protected static final int PK_COLUMN_PRODUCTO_ID_PRODUCTO = 2;

	/** 
	 * Index of primary-key column PROVEEDOR_TIPO_DOCUMENTO
	 */
	protected static final int PK_COLUMN_PROVEEDOR_TIPO_DOCUMENTO = 3;

	/** 
	 * Index of primary-key column PROVEEDOR_NUM_DOCUMENTO
	 */
	protected static final int PK_COLUMN_PROVEEDOR_NUM_DOCUMENTO = 4;

	/** 
	 * Inserts a new row in the inventario_compras table.
	 */
	public InventarioComprasPk insert(InventarioCompras dto) throws InventarioComprasDaoException
	{
		long t1 = System.currentTimeMillis();
		// declare variables
		final boolean isConnSupplied = (userConn != null);
		Connection conn = null;
		PreparedStatement stmt = null;
		ResultSet rs = null;
		
		try {
			// get the user-specified connection or get a connection from the ResourceManager
			conn = isConnSupplied ? userConn : ResourceManager.getConnection();
		
			StringBuffer sql = new StringBuffer();
			StringBuffer values = new StringBuffer();
			sql.append( "INSERT INTO " + getTableName() + " (" );
			int modifiedCount = 0;
			if (dto.isIdInventarioModified()) {
				if (modifiedCount>0) {
					sql.append( ", " );
					values.append( ", " );
				}
		
				sql.append( "ID_INVENTARIO" );
				values.append( "?" );
				modifiedCount++;
			}
		
			if (dto.isProductoIdProductoModified()) {
				if (modifiedCount>0) {
					sql.append( ", " );
					values.append( ", " );
				}
		
				sql.append( "PRODUCTO_ID_PRODUCTO" );
				values.append( "?" );
				modifiedCount++;
			}
		
			if (dto.isCanProCompradoModified()) {
				if (modifiedCount>0) {
					sql.append( ", " );
					values.append( ", " );
				}
		
				sql.append( "CAN_PRO_COMPRADO" );
				values.append( "?" );
				modifiedCount++;
			}
		
			if (dto.isFechaCompraModified()) {
				if (modifiedCount>0) {
					sql.append( ", " );
					values.append( ", " );
				}
		
				sql.append( "FECHA_COMPRA" );
				values.append( "?" );
				modifiedCount++;
			}
		
			if (dto.isProveedorTipoDocumentoModified()) {
				if (modifiedCount>0) {
					sql.append( ", " );
					values.append( ", " );
				}
		
				sql.append( "PROVEEDOR_TIPO_DOCUMENTO" );
				values.append( "?" );
				modifiedCount++;
			}
		
			if (dto.isProveedorNumDocumentoModified()) {
				if (modifiedCount>0) {
					sql.append( ", " );
					values.append( ", " );
				}
		
				sql.append( "PROVEEDOR_NUM_DOCUMENTO" );
				values.append( "?" );
				modifiedCount++;
			}
		
			if (modifiedCount==0) {
				// nothing to insert
				throw new IllegalStateException( "Nothing to insert" );
			}
		
			sql.append( ") VALUES (" );
			sql.append( values );
			sql.append( ")" );
			stmt = conn.prepareStatement( sql.toString(), Statement.RETURN_GENERATED_KEYS );
			int index = 1;
			if (dto.isIdInventarioModified()) {
				stmt.setInt( index++, dto.getIdInventario() );
			}
		
			if (dto.isProductoIdProductoModified()) {
				stmt.setString( index++, dto.getProductoIdProducto() );
			}
		
			if (dto.isCanProCompradoModified()) {
				if (dto.isCanProCompradoNull()) {
					stmt.setNull( index++, java.sql.Types.INTEGER );
				} else {
					stmt.setInt( index++, dto.getCanProComprado() );
				}
		
			}
		
			if (dto.isFechaCompraModified()) {
				stmt.setString( index++, dto.getFechaCompra() );
			}
		
			if (dto.isProveedorTipoDocumentoModified()) {
				stmt.setString( index++, dto.getProveedorTipoDocumento() );
			}
		
			if (dto.isProveedorNumDocumentoModified()) {
				stmt.setString( index++, dto.getProveedorNumDocumento() );
			}
		
			System.out.println( "Executing " + sql.toString() + " with values: " + dto );
			int rows = stmt.executeUpdate();
			long t2 = System.currentTimeMillis();
			System.out.println( rows + " rows affected (" + (t2-t1) + " ms)" );
		
			// retrieve values from auto-increment columns
			rs = stmt.getGeneratedKeys();
			if (rs != null && rs.next()) {
				dto.setIdInventario( rs.getInt( 1 ) );
			}
		
			reset(dto);
			return dto.createPk();
		}
		catch (Exception _e) {
			_e.printStackTrace();
			throw new InventarioComprasDaoException( "Exception: " + _e.getMessage(), _e );
		}
		finally {
			ResourceManager.close(stmt);
			if (!isConnSupplied) {
				ResourceManager.close(conn);
			}
		
		}
		
	}

	/** 
	 * Updates a single row in the inventario_compras table.
	 */
	public void update(InventarioComprasPk pk, InventarioCompras dto) throws InventarioComprasDaoException
	{
		long t1 = System.currentTimeMillis();
		// declare variables
		final boolean isConnSupplied = (userConn != null);
		Connection conn = null;
		PreparedStatement stmt = null;
		
		try {
			// get the user-specified connection or get a connection from the ResourceManager
			conn = isConnSupplied ? userConn : ResourceManager.getConnection();
		
			StringBuffer sql = new StringBuffer();
			sql.append( "UPDATE " + getTableName() + " SET " );
			boolean modified = false;
			if (dto.isIdInventarioModified()) {
				if (modified) {
					sql.append( ", " );
				}
		
				sql.append( "ID_INVENTARIO=?" );
				modified=true;
			}
		
			if (dto.isProductoIdProductoModified()) {
				if (modified) {
					sql.append( ", " );
				}
		
				sql.append( "PRODUCTO_ID_PRODUCTO=?" );
				modified=true;
			}
		
			if (dto.isCanProCompradoModified()) {
				if (modified) {
					sql.append( ", " );
				}
		
				sql.append( "CAN_PRO_COMPRADO=?" );
				modified=true;
			}
		
			if (dto.isFechaCompraModified()) {
				if (modified) {
					sql.append( ", " );
				}
		
				sql.append( "FECHA_COMPRA=?" );
				modified=true;
			}
		
			if (dto.isProveedorTipoDocumentoModified()) {
				if (modified) {
					sql.append( ", " );
				}
		
				sql.append( "PROVEEDOR_TIPO_DOCUMENTO=?" );
				modified=true;
			}
		
			if (dto.isProveedorNumDocumentoModified()) {
				if (modified) {
					sql.append( ", " );
				}
		
				sql.append( "PROVEEDOR_NUM_DOCUMENTO=?" );
				modified=true;
			}
		
			if (!modified) {
				// nothing to update
				return;
			}
		
			sql.append( " WHERE ID_INVENTARIO=? AND PRODUCTO_ID_PRODUCTO=? AND PROVEEDOR_TIPO_DOCUMENTO=? AND PROVEEDOR_NUM_DOCUMENTO=?" );
			System.out.println( "Executing " + sql.toString() + " with values: " + dto );
			stmt = conn.prepareStatement( sql.toString() );
			int index = 1;
			if (dto.isIdInventarioModified()) {
				stmt.setInt( index++, dto.getIdInventario() );
			}
		
			if (dto.isProductoIdProductoModified()) {
				stmt.setString( index++, dto.getProductoIdProducto() );
			}
		
			if (dto.isCanProCompradoModified()) {
				if (dto.isCanProCompradoNull()) {
					stmt.setNull( index++, java.sql.Types.INTEGER );
				} else {
					stmt.setInt( index++, dto.getCanProComprado() );
				}
		
			}
		
			if (dto.isFechaCompraModified()) {
				stmt.setString( index++, dto.getFechaCompra() );
			}
		
			if (dto.isProveedorTipoDocumentoModified()) {
				stmt.setString( index++, dto.getProveedorTipoDocumento() );
			}
		
			if (dto.isProveedorNumDocumentoModified()) {
				stmt.setString( index++, dto.getProveedorNumDocumento() );
			}
		
			stmt.setInt( index++, pk.getIdInventario() );
			stmt.setString( index++, pk.getProductoIdProducto() );
			stmt.setString( index++, pk.getProveedorTipoDocumento() );
			stmt.setString( index++, pk.getProveedorNumDocumento() );
			int rows = stmt.executeUpdate();
			reset(dto);
			long t2 = System.currentTimeMillis();
			System.out.println( rows + " rows affected (" + (t2-t1) + " ms)" );
		}
		catch (Exception _e) {
			_e.printStackTrace();
			throw new InventarioComprasDaoException( "Exception: " + _e.getMessage(), _e );
		}
		finally {
			ResourceManager.close(stmt);
			if (!isConnSupplied) {
				ResourceManager.close(conn);
			}
		
		}
		
	}

	/** 
	 * Deletes a single row in the inventario_compras table.
	 */
	public void delete(InventarioComprasPk pk) throws InventarioComprasDaoException
	{
		long t1 = System.currentTimeMillis();
		// declare variables
		final boolean isConnSupplied = (userConn != null);
		Connection conn = null;
		PreparedStatement stmt = null;
		
		try {
			// get the user-specified connection or get a connection from the ResourceManager
			conn = isConnSupplied ? userConn : ResourceManager.getConnection();
		
			System.out.println( "Executing " + SQL_DELETE + " with PK: " + pk );
			stmt = conn.prepareStatement( SQL_DELETE );
			stmt.setInt( 1, pk.getIdInventario() );
			stmt.setString( 2, pk.getProductoIdProducto() );
			stmt.setString( 3, pk.getProveedorTipoDocumento() );
			stmt.setString( 4, pk.getProveedorNumDocumento() );
			int rows = stmt.executeUpdate();
			long t2 = System.currentTimeMillis();
			System.out.println( rows + " rows affected (" + (t2-t1) + " ms)" );
		}
		catch (Exception _e) {
			_e.printStackTrace();
			throw new InventarioComprasDaoException( "Exception: " + _e.getMessage(), _e );
		}
		finally {
			ResourceManager.close(stmt);
			if (!isConnSupplied) {
				ResourceManager.close(conn);
			}
		
		}
		
	}

	/** 
	 * Returns the rows from the inventario_compras table that matches the specified primary-key value.
	 */
	public InventarioCompras findByPrimaryKey(InventarioComprasPk pk) throws InventarioComprasDaoException
	{
		return findByPrimaryKey( pk.getIdInventario(), pk.getProductoIdProducto(), pk.getProveedorTipoDocumento(), pk.getProveedorNumDocumento() );
	}

	/** 
	 * Returns all rows from the inventario_compras table that match the criteria 'ID_INVENTARIO = :idInventario AND PRODUCTO_ID_PRODUCTO = :productoIdProducto AND PROVEEDOR_TIPO_DOCUMENTO = :proveedorTipoDocumento AND PROVEEDOR_NUM_DOCUMENTO = :proveedorNumDocumento'.
	 */
	public InventarioCompras findByPrimaryKey(int idInventario, String productoIdProducto, String proveedorTipoDocumento, String proveedorNumDocumento) throws InventarioComprasDaoException
	{
		InventarioCompras ret[] = findByDynamicSelect( SQL_SELECT + " WHERE ID_INVENTARIO = ? AND PRODUCTO_ID_PRODUCTO = ? AND PROVEEDOR_TIPO_DOCUMENTO = ? AND PROVEEDOR_NUM_DOCUMENTO = ?", new Object[] {  new Integer(idInventario), productoIdProducto, proveedorTipoDocumento, proveedorNumDocumento } );
		return ret.length==0 ? null : ret[0];
	}

	/** 
	 * Returns all rows from the inventario_compras table that match the criteria ''.
	 */
	public InventarioCompras[] findAll() throws InventarioComprasDaoException
	{
		return findByDynamicSelect( SQL_SELECT + " ORDER BY ID_INVENTARIO, PRODUCTO_ID_PRODUCTO, PROVEEDOR_TIPO_DOCUMENTO, PROVEEDOR_NUM_DOCUMENTO", null );
	}

	/** 
	 * Returns all rows from the inventario_compras table that match the criteria 'PRODUCTO_ID_PRODUCTO = :productoIdProducto'.
	 */
	public InventarioCompras[] findByProducto(String productoIdProducto) throws InventarioComprasDaoException
	{
		return findByDynamicSelect( SQL_SELECT + " WHERE PRODUCTO_ID_PRODUCTO = ?", new Object[] { productoIdProducto } );
	}

	/** 
	 * Returns all rows from the inventario_compras table that match the criteria 'PROVEEDOR_TIPO_DOCUMENTO = :proveedorTipoDocumento AND PROVEEDOR_NUM_DOCUMENTO = :proveedorNumDocumento'.
	 */
	public InventarioCompras[] findByProveedor(String proveedorTipoDocumento, String proveedorNumDocumento) throws InventarioComprasDaoException
	{
		return findByDynamicSelect( SQL_SELECT + " WHERE PROVEEDOR_TIPO_DOCUMENTO = ? AND PROVEEDOR_NUM_DOCUMENTO = ?", new Object[] { proveedorTipoDocumento, proveedorNumDocumento } );
	}

	/** 
	 * Returns all rows from the inventario_compras table that match the criteria 'ID_INVENTARIO = :idInventario'.
	 */
	public InventarioCompras[] findWhereIdInventarioEquals(int idInventario) throws InventarioComprasDaoException
	{
		return findByDynamicSelect( SQL_SELECT + " WHERE ID_INVENTARIO = ? ORDER BY ID_INVENTARIO", new Object[] {  new Integer(idInventario) } );
	}

	/** 
	 * Returns all rows from the inventario_compras table that match the criteria 'PRODUCTO_ID_PRODUCTO = :productoIdProducto'.
	 */
	public InventarioCompras[] findWhereProductoIdProductoEquals(String productoIdProducto) throws InventarioComprasDaoException
	{
		return findByDynamicSelect( SQL_SELECT + " WHERE PRODUCTO_ID_PRODUCTO = ? ORDER BY PRODUCTO_ID_PRODUCTO", new Object[] { productoIdProducto } );
	}

	/** 
	 * Returns all rows from the inventario_compras table that match the criteria 'CAN_PRO_COMPRADO = :canProComprado'.
	 */
	public InventarioCompras[] findWhereCanProCompradoEquals(int canProComprado) throws InventarioComprasDaoException
	{
		return findByDynamicSelect( SQL_SELECT + " WHERE CAN_PRO_COMPRADO = ? ORDER BY CAN_PRO_COMPRADO", new Object[] {  new Integer(canProComprado) } );
	}

	/** 
	 * Returns all rows from the inventario_compras table that match the criteria 'FECHA_COMPRA = :fechaCompra'.
	 */
	public InventarioCompras[] findWhereFechaCompraEquals(String fechaCompra) throws InventarioComprasDaoException
	{
		return findByDynamicSelect( SQL_SELECT + " WHERE FECHA_COMPRA = ? ORDER BY FECHA_COMPRA", new Object[] { fechaCompra } );
	}

	/** 
	 * Returns all rows from the inventario_compras table that match the criteria 'PROVEEDOR_TIPO_DOCUMENTO = :proveedorTipoDocumento'.
	 */
	public InventarioCompras[] findWhereProveedorTipoDocumentoEquals(String proveedorTipoDocumento) throws InventarioComprasDaoException
	{
		return findByDynamicSelect( SQL_SELECT + " WHERE PROVEEDOR_TIPO_DOCUMENTO = ? ORDER BY PROVEEDOR_TIPO_DOCUMENTO", new Object[] { proveedorTipoDocumento } );
	}

	/** 
	 * Returns all rows from the inventario_compras table that match the criteria 'PROVEEDOR_NUM_DOCUMENTO = :proveedorNumDocumento'.
	 */
	public InventarioCompras[] findWhereProveedorNumDocumentoEquals(String proveedorNumDocumento) throws InventarioComprasDaoException
	{
		return findByDynamicSelect( SQL_SELECT + " WHERE PROVEEDOR_NUM_DOCUMENTO = ? ORDER BY PROVEEDOR_NUM_DOCUMENTO", new Object[] { proveedorNumDocumento } );
	}

	/**
	 * Method 'InventarioComprasDaoImpl'
	 * 
	 */
	public InventarioComprasDaoImpl()
	{
	}

	/**
	 * Method 'InventarioComprasDaoImpl'
	 * 
	 * @param userConn
	 */
	public InventarioComprasDaoImpl(final java.sql.Connection userConn)
	{
		this.userConn = userConn;
	}

	/** 
	 * Sets the value of maxRows
	 */
	public void setMaxRows(int maxRows)
	{
		this.maxRows = maxRows;
	}

	/** 
	 * Gets the value of maxRows
	 */
	public int getMaxRows()
	{
		return maxRows;
	}

	/**
	 * Method 'getTableName'
	 * 
	 * @return String
	 */
	public String getTableName()
	{
		return "onlineshop.inventario_compras";
	}

	/** 
	 * Fetches a single row from the result set
	 */
	protected InventarioCompras fetchSingleResult(ResultSet rs) throws SQLException
	{
		if (rs.next()) {
			InventarioCompras dto = new InventarioCompras();
			populateDto( dto, rs);
			return dto;
		} else {
			return null;
		}
		
	}

	/** 
	 * Fetches multiple rows from the result set
	 */
	protected InventarioCompras[] fetchMultiResults(ResultSet rs) throws SQLException
	{
		Collection resultList = new ArrayList();
		while (rs.next()) {
			InventarioCompras dto = new InventarioCompras();
			populateDto( dto, rs);
			resultList.add( dto );
		}
		
		InventarioCompras ret[] = new InventarioCompras[ resultList.size() ];
		resultList.toArray( ret );
		return ret;
	}

	/** 
	 * Populates a DTO with data from a ResultSet
	 */
	protected void populateDto(InventarioCompras dto, ResultSet rs) throws SQLException
	{
		dto.setIdInventario( rs.getInt( COLUMN_ID_INVENTARIO ) );
		dto.setProductoIdProducto( rs.getString( COLUMN_PRODUCTO_ID_PRODUCTO ) );
		dto.setCanProComprado( rs.getInt( COLUMN_CAN_PRO_COMPRADO ) );
		if (rs.wasNull()) {
			dto.setCanProCompradoNull( true );
		}
		
		dto.setFechaCompra( rs.getString( COLUMN_FECHA_COMPRA ) );
		dto.setProveedorTipoDocumento( rs.getString( COLUMN_PROVEEDOR_TIPO_DOCUMENTO ) );
		dto.setProveedorNumDocumento( rs.getString( COLUMN_PROVEEDOR_NUM_DOCUMENTO ) );
		reset(dto);
	}

	/** 
	 * Resets the modified attributes in the DTO
	 */
	protected void reset(InventarioCompras dto)
	{
		dto.setIdInventarioModified( false );
		dto.setProductoIdProductoModified( false );
		dto.setCanProCompradoModified( false );
		dto.setFechaCompraModified( false );
		dto.setProveedorTipoDocumentoModified( false );
		dto.setProveedorNumDocumentoModified( false );
	}

	/** 
	 * Returns all rows from the inventario_compras table that match the specified arbitrary SQL statement
	 */
	public InventarioCompras[] findByDynamicSelect(String sql, Object[] sqlParams) throws InventarioComprasDaoException
	{
		// declare variables
		final boolean isConnSupplied = (userConn != null);
		Connection conn = null;
		PreparedStatement stmt = null;
		ResultSet rs = null;
		
		try {
			// get the user-specified connection or get a connection from the ResourceManager
			conn = isConnSupplied ? userConn : ResourceManager.getConnection();
		
			// construct the SQL statement
			final String SQL = sql;
		
		
			System.out.println( "Executing " + SQL );
			// prepare statement
			stmt = conn.prepareStatement( SQL );
			stmt.setMaxRows( maxRows );
		
			// bind parameters
			for (int i=0; sqlParams!=null && i<sqlParams.length; i++ ) {
				stmt.setObject( i+1, sqlParams[i] );
			}
		
		
			rs = stmt.executeQuery();
		
			// fetch the results
			return fetchMultiResults(rs);
		}
		catch (Exception _e) {
			_e.printStackTrace();
			throw new InventarioComprasDaoException( "Exception: " + _e.getMessage(), _e );
		}
		finally {
			ResourceManager.close(rs);
			ResourceManager.close(stmt);
			if (!isConnSupplied) {
				ResourceManager.close(conn);
			}
		
		}
		
	}

	/** 
	 * Returns all rows from the inventario_compras table that match the specified arbitrary SQL statement
	 */
	public InventarioCompras[] findByDynamicWhere(String sql, Object[] sqlParams) throws InventarioComprasDaoException
	{
		// declare variables
		final boolean isConnSupplied = (userConn != null);
		Connection conn = null;
		PreparedStatement stmt = null;
		ResultSet rs = null;
		
		try {
			// get the user-specified connection or get a connection from the ResourceManager
			conn = isConnSupplied ? userConn : ResourceManager.getConnection();
		
			// construct the SQL statement
			final String SQL = SQL_SELECT + " WHERE " + sql;
		
		
			System.out.println( "Executing " + SQL );
			// prepare statement
			stmt = conn.prepareStatement( SQL );
			stmt.setMaxRows( maxRows );
		
			// bind parameters
			for (int i=0; sqlParams!=null && i<sqlParams.length; i++ ) {
				stmt.setObject( i+1, sqlParams[i] );
			}
		
		
			rs = stmt.executeQuery();
		
			// fetch the results
			return fetchMultiResults(rs);
		}
		catch (Exception _e) {
			_e.printStackTrace();
			throw new InventarioComprasDaoException( "Exception: " + _e.getMessage(), _e );
		}
		finally {
			ResourceManager.close(rs);
			ResourceManager.close(stmt);
			if (!isConnSupplied) {
				ResourceManager.close(conn);
			}
		
		}
		
	}

}
