/*
 * This source file was generated by FireStorm/DAO.
 * 
 * If you purchase a full license for FireStorm/DAO you can customize this header file.
 * 
 * For more information please visit http://www.codefutures.com/products/firestorm
 */

package edu.co.sena.onlineshop.integracion.dto;

import edu.co.sena.onlineshop.integracion.dao.*;
import edu.co.sena.onlineshop.integracion.factory.*;
import edu.co.sena.onlineshop.integracion.exceptions.*;
import java.io.Serializable;
import java.util.*;

public class Municipio implements Serializable
{
	/** 
	 * This attribute maps to the column idMUNICIPIO in the municipio table.
	 */
	protected int idMUNICIPIO;

	/** 
	 * This attribute represents whether the attribute idMUNICIPIO has been modified since being read from the database.
	 */
	protected boolean idMUNICIPIOModified = false;

	/** 
	 * This attribute maps to the column NOMBRE_MUNICIPIO in the municipio table.
	 */
	protected String nombreMunicipio;

	/** 
	 * This attribute represents whether the attribute nombreMunicipio has been modified since being read from the database.
	 */
	protected boolean nombreMunicipioModified = false;

	/** 
	 * This attribute maps to the column DEPARTAMENTO_idDEPARTAMENTO in the municipio table.
	 */
	protected int departamentoIddepartamento;

	/** 
	 * This attribute represents whether the attribute departamentoIddepartamento has been modified since being read from the database.
	 */
	protected boolean departamentoIddepartamentoModified = false;

	/**
	 * Method 'Municipio'
	 * 
	 */
	public Municipio()
	{
	}

	/**
	 * Method 'getIdMUNICIPIO'
	 * 
	 * @return int
	 */
	public int getIdMUNICIPIO()
	{
		return idMUNICIPIO;
	}

	/**
	 * Method 'setIdMUNICIPIO'
	 * 
	 * @param idMUNICIPIO
	 */
	public void setIdMUNICIPIO(int idMUNICIPIO)
	{
		this.idMUNICIPIO = idMUNICIPIO;
		this.idMUNICIPIOModified = true;
	}

	/** 
	 * Sets the value of idMUNICIPIOModified
	 */
	public void setIdMUNICIPIOModified(boolean idMUNICIPIOModified)
	{
		this.idMUNICIPIOModified = idMUNICIPIOModified;
	}

	/** 
	 * Gets the value of idMUNICIPIOModified
	 */
	public boolean isIdMUNICIPIOModified()
	{
		return idMUNICIPIOModified;
	}

	/**
	 * Method 'getNombreMunicipio'
	 * 
	 * @return String
	 */
	public String getNombreMunicipio()
	{
		return nombreMunicipio;
	}

	/**
	 * Method 'setNombreMunicipio'
	 * 
	 * @param nombreMunicipio
	 */
	public void setNombreMunicipio(String nombreMunicipio)
	{
		this.nombreMunicipio = nombreMunicipio;
		this.nombreMunicipioModified = true;
	}

	/** 
	 * Sets the value of nombreMunicipioModified
	 */
	public void setNombreMunicipioModified(boolean nombreMunicipioModified)
	{
		this.nombreMunicipioModified = nombreMunicipioModified;
	}

	/** 
	 * Gets the value of nombreMunicipioModified
	 */
	public boolean isNombreMunicipioModified()
	{
		return nombreMunicipioModified;
	}

	/**
	 * Method 'getDepartamentoIddepartamento'
	 * 
	 * @return int
	 */
	public int getDepartamentoIddepartamento()
	{
		return departamentoIddepartamento;
	}

	/**
	 * Method 'setDepartamentoIddepartamento'
	 * 
	 * @param departamentoIddepartamento
	 */
	public void setDepartamentoIddepartamento(int departamentoIddepartamento)
	{
		this.departamentoIddepartamento = departamentoIddepartamento;
		this.departamentoIddepartamentoModified = true;
	}

	/** 
	 * Sets the value of departamentoIddepartamentoModified
	 */
	public void setDepartamentoIddepartamentoModified(boolean departamentoIddepartamentoModified)
	{
		this.departamentoIddepartamentoModified = departamentoIddepartamentoModified;
	}

	/** 
	 * Gets the value of departamentoIddepartamentoModified
	 */
	public boolean isDepartamentoIddepartamentoModified()
	{
		return departamentoIddepartamentoModified;
	}

	/**
	 * Method 'equals'
	 * 
	 * @param _other
	 * @return boolean
	 */
	public boolean equals(Object _other)
	{
		if (_other == null) {
			return false;
		}
		
		if (_other == this) {
			return true;
		}
		
		if (!(_other instanceof Municipio)) {
			return false;
		}
		
		final Municipio _cast = (Municipio) _other;
		if (idMUNICIPIO != _cast.idMUNICIPIO) {
			return false;
		}
		
		if (idMUNICIPIOModified != _cast.idMUNICIPIOModified) {
			return false;
		}
		
		if (nombreMunicipio == null ? _cast.nombreMunicipio != nombreMunicipio : !nombreMunicipio.equals( _cast.nombreMunicipio )) {
			return false;
		}
		
		if (nombreMunicipioModified != _cast.nombreMunicipioModified) {
			return false;
		}
		
		if (departamentoIddepartamento != _cast.departamentoIddepartamento) {
			return false;
		}
		
		if (departamentoIddepartamentoModified != _cast.departamentoIddepartamentoModified) {
			return false;
		}
		
		return true;
	}

	/**
	 * Method 'hashCode'
	 * 
	 * @return int
	 */
	public int hashCode()
	{
		int _hashCode = 0;
		_hashCode = 29 * _hashCode + idMUNICIPIO;
		_hashCode = 29 * _hashCode + (idMUNICIPIOModified ? 1 : 0);
		if (nombreMunicipio != null) {
			_hashCode = 29 * _hashCode + nombreMunicipio.hashCode();
		}
		
		_hashCode = 29 * _hashCode + (nombreMunicipioModified ? 1 : 0);
		_hashCode = 29 * _hashCode + departamentoIddepartamento;
		_hashCode = 29 * _hashCode + (departamentoIddepartamentoModified ? 1 : 0);
		return _hashCode;
	}

	/**
	 * Method 'createPk'
	 * 
	 * @return MunicipioPk
	 */
	public MunicipioPk createPk()
	{
		return new MunicipioPk(idMUNICIPIO);
	}

	/**
	 * Method 'toString'
	 * 
	 * @return String
	 */
	public String toString()
	{
		StringBuffer ret = new StringBuffer();
		ret.append( "edu.co.sena.onlineshop.integracion.dto.Municipio: " );
		ret.append( "idMUNICIPIO=" + idMUNICIPIO );
		ret.append( ", nombreMunicipio=" + nombreMunicipio );
		ret.append( ", departamentoIddepartamento=" + departamentoIddepartamento );
		return ret.toString();
	}

}
