/*
 * This source file was generated by FireStorm/DAO.
 * 
 * If you purchase a full license for FireStorm/DAO you can customize this header file.
 * 
 * For more information please visit http://www.codefutures.com/products/firestorm
 */

package edu.co.sena.onlineshop.integracion.dto;

import edu.co.sena.onlineshop.integracion.dao.*;
import edu.co.sena.onlineshop.integracion.factory.*;
import edu.co.sena.onlineshop.integracion.exceptions.*;
import java.io.Serializable;
import java.util.*;

public class Pedido implements Serializable
{
	/** 
	 * This attribute maps to the column FACTURA_ID_FACTURA in the pedido table.
	 */
	protected int facturaIdFactura;

	/** 
	 * This attribute represents whether the attribute facturaIdFactura has been modified since being read from the database.
	 */
	protected boolean facturaIdFacturaModified = false;

	/** 
	 * This attribute maps to the column TOTAL in the pedido table.
	 */
	protected double total;

	/** 
	 * This attribute represents whether the attribute total has been modified since being read from the database.
	 */
	protected boolean totalModified = false;

	/** 
	 * This attribute maps to the column SUBTOTAL in the pedido table.
	 */
	protected double subtotal;

	/** 
	 * This attribute represents whether the attribute subtotal has been modified since being read from the database.
	 */
	protected boolean subtotalModified = false;

	/** 
	 * This attribute maps to the column IMPUESTOS in the pedido table.
	 */
	protected double impuestos;

	/** 
	 * This attribute represents whether the attribute impuestos has been modified since being read from the database.
	 */
	protected boolean impuestosModified = false;

	/**
	 * Method 'Pedido'
	 * 
	 */
	public Pedido()
	{
	}

	/**
	 * Method 'getFacturaIdFactura'
	 * 
	 * @return int
	 */
	public int getFacturaIdFactura()
	{
		return facturaIdFactura;
	}

	/**
	 * Method 'setFacturaIdFactura'
	 * 
	 * @param facturaIdFactura
	 */
	public void setFacturaIdFactura(int facturaIdFactura)
	{
		this.facturaIdFactura = facturaIdFactura;
		this.facturaIdFacturaModified = true;
	}

	/** 
	 * Sets the value of facturaIdFacturaModified
	 */
	public void setFacturaIdFacturaModified(boolean facturaIdFacturaModified)
	{
		this.facturaIdFacturaModified = facturaIdFacturaModified;
	}

	/** 
	 * Gets the value of facturaIdFacturaModified
	 */
	public boolean isFacturaIdFacturaModified()
	{
		return facturaIdFacturaModified;
	}

	/**
	 * Method 'getTotal'
	 * 
	 * @return double
	 */
	public double getTotal()
	{
		return total;
	}

	/**
	 * Method 'setTotal'
	 * 
	 * @param total
	 */
	public void setTotal(double total)
	{
		this.total = total;
		this.totalModified = true;
	}

	/** 
	 * Sets the value of totalModified
	 */
	public void setTotalModified(boolean totalModified)
	{
		this.totalModified = totalModified;
	}

	/** 
	 * Gets the value of totalModified
	 */
	public boolean isTotalModified()
	{
		return totalModified;
	}

	/**
	 * Method 'getSubtotal'
	 * 
	 * @return double
	 */
	public double getSubtotal()
	{
		return subtotal;
	}

	/**
	 * Method 'setSubtotal'
	 * 
	 * @param subtotal
	 */
	public void setSubtotal(double subtotal)
	{
		this.subtotal = subtotal;
		this.subtotalModified = true;
	}

	/** 
	 * Sets the value of subtotalModified
	 */
	public void setSubtotalModified(boolean subtotalModified)
	{
		this.subtotalModified = subtotalModified;
	}

	/** 
	 * Gets the value of subtotalModified
	 */
	public boolean isSubtotalModified()
	{
		return subtotalModified;
	}

	/**
	 * Method 'getImpuestos'
	 * 
	 * @return double
	 */
	public double getImpuestos()
	{
		return impuestos;
	}

	/**
	 * Method 'setImpuestos'
	 * 
	 * @param impuestos
	 */
	public void setImpuestos(double impuestos)
	{
		this.impuestos = impuestos;
		this.impuestosModified = true;
	}

	/** 
	 * Sets the value of impuestosModified
	 */
	public void setImpuestosModified(boolean impuestosModified)
	{
		this.impuestosModified = impuestosModified;
	}

	/** 
	 * Gets the value of impuestosModified
	 */
	public boolean isImpuestosModified()
	{
		return impuestosModified;
	}

	/**
	 * Method 'equals'
	 * 
	 * @param _other
	 * @return boolean
	 */
	public boolean equals(Object _other)
	{
		if (_other == null) {
			return false;
		}
		
		if (_other == this) {
			return true;
		}
		
		if (!(_other instanceof Pedido)) {
			return false;
		}
		
		final Pedido _cast = (Pedido) _other;
		if (facturaIdFactura != _cast.facturaIdFactura) {
			return false;
		}
		
		if (facturaIdFacturaModified != _cast.facturaIdFacturaModified) {
			return false;
		}
		
		if (total != _cast.total) {
			return false;
		}
		
		if (totalModified != _cast.totalModified) {
			return false;
		}
		
		if (subtotal != _cast.subtotal) {
			return false;
		}
		
		if (subtotalModified != _cast.subtotalModified) {
			return false;
		}
		
		if (impuestos != _cast.impuestos) {
			return false;
		}
		
		if (impuestosModified != _cast.impuestosModified) {
			return false;
		}
		
		return true;
	}

	/**
	 * Method 'hashCode'
	 * 
	 * @return int
	 */
	public int hashCode()
	{
		int _hashCode = 0;
		_hashCode = 29 * _hashCode + facturaIdFactura;
		_hashCode = 29 * _hashCode + (facturaIdFacturaModified ? 1 : 0);
		long temp_total = Double.doubleToLongBits(total);
		_hashCode = 29 * _hashCode + (int) (temp_total ^ (temp_total >>> 32));
		_hashCode = 29 * _hashCode + (totalModified ? 1 : 0);
		long temp_subtotal = Double.doubleToLongBits(subtotal);
		_hashCode = 29 * _hashCode + (int) (temp_subtotal ^ (temp_subtotal >>> 32));
		_hashCode = 29 * _hashCode + (subtotalModified ? 1 : 0);
		long temp_impuestos = Double.doubleToLongBits(impuestos);
		_hashCode = 29 * _hashCode + (int) (temp_impuestos ^ (temp_impuestos >>> 32));
		_hashCode = 29 * _hashCode + (impuestosModified ? 1 : 0);
		return _hashCode;
	}

	/**
	 * Method 'createPk'
	 * 
	 * @return PedidoPk
	 */
	public PedidoPk createPk()
	{
		return new PedidoPk(facturaIdFactura);
	}

	/**
	 * Method 'toString'
	 * 
	 * @return String
	 */
	public String toString()
	{
		StringBuffer ret = new StringBuffer();
		ret.append( "edu.co.sena.onlineshop.integracion.dto.Pedido: " );
		ret.append( "facturaIdFactura=" + facturaIdFactura );
		ret.append( ", total=" + total );
		ret.append( ", subtotal=" + subtotal );
		ret.append( ", impuestos=" + impuestos );
		return ret.toString();
	}

}
