/*
 * This source file was generated by FireStorm/DAO.
 * 
 * If you purchase a full license for FireStorm/DAO you can customize this header file.
 * 
 * For more information please visit http://www.codefutures.com/products/firestorm
 */

package edu.co.sena.onlineshop.integracion.dto;

import edu.co.sena.onlineshop.integracion.dao.*;
import edu.co.sena.onlineshop.integracion.factory.*;
import edu.co.sena.onlineshop.integracion.exceptions.*;
import java.io.Serializable;
import java.util.*;
import java.util.Date;

public class Producto implements Serializable
{
	/** 
	 * This attribute maps to the column ID_PRODUCTO in the producto table.
	 */
	protected String idProducto;

	/** 
	 * This attribute represents whether the attribute idProducto has been modified since being read from the database.
	 */
	protected boolean idProductoModified = false;

	/** 
	 * This attribute maps to the column NOMBRE_PRODUCTO in the producto table.
	 */
	protected String nombreProducto;

	/** 
	 * This attribute represents whether the attribute nombreProducto has been modified since being read from the database.
	 */
	protected boolean nombreProductoModified = false;

	/** 
	 * This attribute maps to the column PRECIO in the producto table.
	 */
	protected double precio;

	/** 
	 * This attribute represents whether the attribute precio has been modified since being read from the database.
	 */
	protected boolean precioModified = false;

	/** 
	 * This attribute maps to the column IMAGEN in the producto table.
	 */
	protected byte[] imagen;

	/** 
	 * This attribute represents whether the attribute imagen has been modified since being read from the database.
	 */
	protected boolean imagenModified = false;

	/** 
	 * This attribute maps to the column CANTIDAD in the producto table.
	 */
	protected float cantidad;

	/** 
	 * This attribute represents whether the primitive attribute cantidad is null.
	 */
	protected boolean cantidadNull = true;

	/** 
	 * This attribute represents whether the attribute cantidad has been modified since being read from the database.
	 */
	protected boolean cantidadModified = false;

	/** 
	 * This attribute maps to the column ACTIVO in the producto table.
	 */
	protected short activo;

	/** 
	 * This attribute represents whether the attribute activo has been modified since being read from the database.
	 */
	protected boolean activoModified = false;

	/** 
	 * This attribute maps to the column FECHA_CREACION in the producto table.
	 */
	protected Date fechaCreacion;

	/** 
	 * This attribute represents whether the attribute fechaCreacion has been modified since being read from the database.
	 */
	protected boolean fechaCreacionModified = false;

	/** 
	 * This attribute maps to the column USUARIO_CREACION in the producto table.
	 */
	protected String usuarioCreacion;

	/** 
	 * This attribute represents whether the attribute usuarioCreacion has been modified since being read from the database.
	 */
	protected boolean usuarioCreacionModified = false;

	/** 
	 * This attribute maps to the column FECHA_ULTIMA_MODIFICACION in the producto table.
	 */
	protected Date fechaUltimaModificacion;

	/** 
	 * This attribute represents whether the attribute fechaUltimaModificacion has been modified since being read from the database.
	 */
	protected boolean fechaUltimaModificacionModified = false;

	/** 
	 * This attribute maps to the column USUARIO_ULTIMA_MODIFICACION in the producto table.
	 */
	protected String usuarioUltimaModificacion;

	/** 
	 * This attribute represents whether the attribute usuarioUltimaModificacion has been modified since being read from the database.
	 */
	protected boolean usuarioUltimaModificacionModified = false;

	/** 
	 * This attribute maps to the column CATEGORIA_ID_CATEGORIA in the producto table.
	 */
	protected int categoriaIdCategoria;

	/** 
	 * This attribute represents whether the attribute categoriaIdCategoria has been modified since being read from the database.
	 */
	protected boolean categoriaIdCategoriaModified = false;

	/** 
	 * This attribute maps to the column CATALOGO_ID_CATALOGO in the producto table.
	 */
	protected int catalogoIdCatalogo;

	/** 
	 * This attribute represents whether the attribute catalogoIdCatalogo has been modified since being read from the database.
	 */
	protected boolean catalogoIdCatalogoModified = false;

	/**
	 * Method 'Producto'
	 * 
	 */
	public Producto()
	{
	}

	/**
	 * Method 'getIdProducto'
	 * 
	 * @return String
	 */
	public String getIdProducto()
	{
		return idProducto;
	}

	/**
	 * Method 'setIdProducto'
	 * 
	 * @param idProducto
	 */
	public void setIdProducto(String idProducto)
	{
		this.idProducto = idProducto;
		this.idProductoModified = true;
	}

	/** 
	 * Sets the value of idProductoModified
	 */
	public void setIdProductoModified(boolean idProductoModified)
	{
		this.idProductoModified = idProductoModified;
	}

	/** 
	 * Gets the value of idProductoModified
	 */
	public boolean isIdProductoModified()
	{
		return idProductoModified;
	}

	/**
	 * Method 'getNombreProducto'
	 * 
	 * @return String
	 */
	public String getNombreProducto()
	{
		return nombreProducto;
	}

	/**
	 * Method 'setNombreProducto'
	 * 
	 * @param nombreProducto
	 */
	public void setNombreProducto(String nombreProducto)
	{
		this.nombreProducto = nombreProducto;
		this.nombreProductoModified = true;
	}

	/** 
	 * Sets the value of nombreProductoModified
	 */
	public void setNombreProductoModified(boolean nombreProductoModified)
	{
		this.nombreProductoModified = nombreProductoModified;
	}

	/** 
	 * Gets the value of nombreProductoModified
	 */
	public boolean isNombreProductoModified()
	{
		return nombreProductoModified;
	}

	/**
	 * Method 'getPrecio'
	 * 
	 * @return double
	 */
	public double getPrecio()
	{
		return precio;
	}

	/**
	 * Method 'setPrecio'
	 * 
	 * @param precio
	 */
	public void setPrecio(double precio)
	{
		this.precio = precio;
		this.precioModified = true;
	}

	/** 
	 * Sets the value of precioModified
	 */
	public void setPrecioModified(boolean precioModified)
	{
		this.precioModified = precioModified;
	}

	/** 
	 * Gets the value of precioModified
	 */
	public boolean isPrecioModified()
	{
		return precioModified;
	}

	/**
	 * Method 'getImagen'
	 * 
	 * @return byte[]
	 */
	public byte[] getImagen()
	{
		return imagen;
	}

	/**
	 * Method 'setImagen'
	 * 
	 * @param imagen
	 */
	public void setImagen(byte[] imagen)
	{
		this.imagen = imagen;
		this.imagenModified = true;
	}

	/** 
	 * Sets the value of imagenModified
	 */
	public void setImagenModified(boolean imagenModified)
	{
		this.imagenModified = imagenModified;
	}

	/** 
	 * Gets the value of imagenModified
	 */
	public boolean isImagenModified()
	{
		return imagenModified;
	}

	/**
	 * Method 'getCantidad'
	 * 
	 * @return float
	 */
	public float getCantidad()
	{
		return cantidad;
	}

	/**
	 * Method 'setCantidad'
	 * 
	 * @param cantidad
	 */
	public void setCantidad(float cantidad)
	{
		this.cantidad = cantidad;
		this.cantidadNull = false;
		this.cantidadModified = true;
	}

	/**
	 * Method 'setCantidadNull'
	 * 
	 * @param value
	 */
	public void setCantidadNull(boolean value)
	{
		this.cantidadNull = value;
		this.cantidadModified = true;
	}

	/**
	 * Method 'isCantidadNull'
	 * 
	 * @return boolean
	 */
	public boolean isCantidadNull()
	{
		return cantidadNull;
	}

	/** 
	 * Sets the value of cantidadModified
	 */
	public void setCantidadModified(boolean cantidadModified)
	{
		this.cantidadModified = cantidadModified;
	}

	/** 
	 * Gets the value of cantidadModified
	 */
	public boolean isCantidadModified()
	{
		return cantidadModified;
	}

	/**
	 * Method 'getActivo'
	 * 
	 * @return short
	 */
	public short getActivo()
	{
		return activo;
	}

	/**
	 * Method 'setActivo'
	 * 
	 * @param activo
	 */
	public void setActivo(short activo)
	{
		this.activo = activo;
		this.activoModified = true;
	}

	/** 
	 * Sets the value of activoModified
	 */
	public void setActivoModified(boolean activoModified)
	{
		this.activoModified = activoModified;
	}

	/** 
	 * Gets the value of activoModified
	 */
	public boolean isActivoModified()
	{
		return activoModified;
	}

	/**
	 * Method 'getFechaCreacion'
	 * 
	 * @return Date
	 */
	public Date getFechaCreacion()
	{
		return fechaCreacion;
	}

	/**
	 * Method 'setFechaCreacion'
	 * 
	 * @param fechaCreacion
	 */
	public void setFechaCreacion(Date fechaCreacion)
	{
		this.fechaCreacion = fechaCreacion;
		this.fechaCreacionModified = true;
	}

	/** 
	 * Sets the value of fechaCreacionModified
	 */
	public void setFechaCreacionModified(boolean fechaCreacionModified)
	{
		this.fechaCreacionModified = fechaCreacionModified;
	}

	/** 
	 * Gets the value of fechaCreacionModified
	 */
	public boolean isFechaCreacionModified()
	{
		return fechaCreacionModified;
	}

	/**
	 * Method 'getUsuarioCreacion'
	 * 
	 * @return String
	 */
	public String getUsuarioCreacion()
	{
		return usuarioCreacion;
	}

	/**
	 * Method 'setUsuarioCreacion'
	 * 
	 * @param usuarioCreacion
	 */
	public void setUsuarioCreacion(String usuarioCreacion)
	{
		this.usuarioCreacion = usuarioCreacion;
		this.usuarioCreacionModified = true;
	}

	/** 
	 * Sets the value of usuarioCreacionModified
	 */
	public void setUsuarioCreacionModified(boolean usuarioCreacionModified)
	{
		this.usuarioCreacionModified = usuarioCreacionModified;
	}

	/** 
	 * Gets the value of usuarioCreacionModified
	 */
	public boolean isUsuarioCreacionModified()
	{
		return usuarioCreacionModified;
	}

	/**
	 * Method 'getFechaUltimaModificacion'
	 * 
	 * @return Date
	 */
	public Date getFechaUltimaModificacion()
	{
		return fechaUltimaModificacion;
	}

	/**
	 * Method 'setFechaUltimaModificacion'
	 * 
	 * @param fechaUltimaModificacion
	 */
	public void setFechaUltimaModificacion(Date fechaUltimaModificacion)
	{
		this.fechaUltimaModificacion = fechaUltimaModificacion;
		this.fechaUltimaModificacionModified = true;
	}

	/** 
	 * Sets the value of fechaUltimaModificacionModified
	 */
	public void setFechaUltimaModificacionModified(boolean fechaUltimaModificacionModified)
	{
		this.fechaUltimaModificacionModified = fechaUltimaModificacionModified;
	}

	/** 
	 * Gets the value of fechaUltimaModificacionModified
	 */
	public boolean isFechaUltimaModificacionModified()
	{
		return fechaUltimaModificacionModified;
	}

	/**
	 * Method 'getUsuarioUltimaModificacion'
	 * 
	 * @return String
	 */
	public String getUsuarioUltimaModificacion()
	{
		return usuarioUltimaModificacion;
	}

	/**
	 * Method 'setUsuarioUltimaModificacion'
	 * 
	 * @param usuarioUltimaModificacion
	 */
	public void setUsuarioUltimaModificacion(String usuarioUltimaModificacion)
	{
		this.usuarioUltimaModificacion = usuarioUltimaModificacion;
		this.usuarioUltimaModificacionModified = true;
	}

	/** 
	 * Sets the value of usuarioUltimaModificacionModified
	 */
	public void setUsuarioUltimaModificacionModified(boolean usuarioUltimaModificacionModified)
	{
		this.usuarioUltimaModificacionModified = usuarioUltimaModificacionModified;
	}

	/** 
	 * Gets the value of usuarioUltimaModificacionModified
	 */
	public boolean isUsuarioUltimaModificacionModified()
	{
		return usuarioUltimaModificacionModified;
	}

	/**
	 * Method 'getCategoriaIdCategoria'
	 * 
	 * @return int
	 */
	public int getCategoriaIdCategoria()
	{
		return categoriaIdCategoria;
	}

	/**
	 * Method 'setCategoriaIdCategoria'
	 * 
	 * @param categoriaIdCategoria
	 */
	public void setCategoriaIdCategoria(int categoriaIdCategoria)
	{
		this.categoriaIdCategoria = categoriaIdCategoria;
		this.categoriaIdCategoriaModified = true;
	}

	/** 
	 * Sets the value of categoriaIdCategoriaModified
	 */
	public void setCategoriaIdCategoriaModified(boolean categoriaIdCategoriaModified)
	{
		this.categoriaIdCategoriaModified = categoriaIdCategoriaModified;
	}

	/** 
	 * Gets the value of categoriaIdCategoriaModified
	 */
	public boolean isCategoriaIdCategoriaModified()
	{
		return categoriaIdCategoriaModified;
	}

	/**
	 * Method 'getCatalogoIdCatalogo'
	 * 
	 * @return int
	 */
	public int getCatalogoIdCatalogo()
	{
		return catalogoIdCatalogo;
	}

	/**
	 * Method 'setCatalogoIdCatalogo'
	 * 
	 * @param catalogoIdCatalogo
	 */
	public void setCatalogoIdCatalogo(int catalogoIdCatalogo)
	{
		this.catalogoIdCatalogo = catalogoIdCatalogo;
		this.catalogoIdCatalogoModified = true;
	}

	/** 
	 * Sets the value of catalogoIdCatalogoModified
	 */
	public void setCatalogoIdCatalogoModified(boolean catalogoIdCatalogoModified)
	{
		this.catalogoIdCatalogoModified = catalogoIdCatalogoModified;
	}

	/** 
	 * Gets the value of catalogoIdCatalogoModified
	 */
	public boolean isCatalogoIdCatalogoModified()
	{
		return catalogoIdCatalogoModified;
	}

	/**
	 * Method 'equals'
	 * 
	 * @param _other
	 * @return boolean
	 */
	public boolean equals(Object _other)
	{
		if (_other == null) {
			return false;
		}
		
		if (_other == this) {
			return true;
		}
		
		if (!(_other instanceof Producto)) {
			return false;
		}
		
		final Producto _cast = (Producto) _other;
		if (idProducto == null ? _cast.idProducto != idProducto : !idProducto.equals( _cast.idProducto )) {
			return false;
		}
		
		if (idProductoModified != _cast.idProductoModified) {
			return false;
		}
		
		if (nombreProducto == null ? _cast.nombreProducto != nombreProducto : !nombreProducto.equals( _cast.nombreProducto )) {
			return false;
		}
		
		if (nombreProductoModified != _cast.nombreProductoModified) {
			return false;
		}
		
		if (precio != _cast.precio) {
			return false;
		}
		
		if (precioModified != _cast.precioModified) {
			return false;
		}
		
		if (imagen == null ? _cast.imagen != imagen : !imagen.equals( _cast.imagen )) {
			return false;
		}
		
		if (imagenModified != _cast.imagenModified) {
			return false;
		}
		
		if (cantidad != _cast.cantidad) {
			return false;
		}
		
		if (cantidadNull != _cast.cantidadNull) {
			return false;
		}
		
		if (cantidadModified != _cast.cantidadModified) {
			return false;
		}
		
		if (activo != _cast.activo) {
			return false;
		}
		
		if (activoModified != _cast.activoModified) {
			return false;
		}
		
		if (fechaCreacion == null ? _cast.fechaCreacion != fechaCreacion : !fechaCreacion.equals( _cast.fechaCreacion )) {
			return false;
		}
		
		if (fechaCreacionModified != _cast.fechaCreacionModified) {
			return false;
		}
		
		if (usuarioCreacion == null ? _cast.usuarioCreacion != usuarioCreacion : !usuarioCreacion.equals( _cast.usuarioCreacion )) {
			return false;
		}
		
		if (usuarioCreacionModified != _cast.usuarioCreacionModified) {
			return false;
		}
		
		if (fechaUltimaModificacion == null ? _cast.fechaUltimaModificacion != fechaUltimaModificacion : !fechaUltimaModificacion.equals( _cast.fechaUltimaModificacion )) {
			return false;
		}
		
		if (fechaUltimaModificacionModified != _cast.fechaUltimaModificacionModified) {
			return false;
		}
		
		if (usuarioUltimaModificacion == null ? _cast.usuarioUltimaModificacion != usuarioUltimaModificacion : !usuarioUltimaModificacion.equals( _cast.usuarioUltimaModificacion )) {
			return false;
		}
		
		if (usuarioUltimaModificacionModified != _cast.usuarioUltimaModificacionModified) {
			return false;
		}
		
		if (categoriaIdCategoria != _cast.categoriaIdCategoria) {
			return false;
		}
		
		if (categoriaIdCategoriaModified != _cast.categoriaIdCategoriaModified) {
			return false;
		}
		
		if (catalogoIdCatalogo != _cast.catalogoIdCatalogo) {
			return false;
		}
		
		if (catalogoIdCatalogoModified != _cast.catalogoIdCatalogoModified) {
			return false;
		}
		
		return true;
	}

	/**
	 * Method 'hashCode'
	 * 
	 * @return int
	 */
	public int hashCode()
	{
		int _hashCode = 0;
		if (idProducto != null) {
			_hashCode = 29 * _hashCode + idProducto.hashCode();
		}
		
		_hashCode = 29 * _hashCode + (idProductoModified ? 1 : 0);
		if (nombreProducto != null) {
			_hashCode = 29 * _hashCode + nombreProducto.hashCode();
		}
		
		_hashCode = 29 * _hashCode + (nombreProductoModified ? 1 : 0);
		long temp_precio = Double.doubleToLongBits(precio);
		_hashCode = 29 * _hashCode + (int) (temp_precio ^ (temp_precio >>> 32));
		_hashCode = 29 * _hashCode + (precioModified ? 1 : 0);
		if (imagen != null) {
			_hashCode = 29 * _hashCode + imagen.hashCode();
		}
		
		_hashCode = 29 * _hashCode + (imagenModified ? 1 : 0);
		_hashCode = 29 * _hashCode + Float.floatToIntBits(cantidad);
		_hashCode = 29 * _hashCode + (cantidadNull ? 1 : 0);
		_hashCode = 29 * _hashCode + (cantidadModified ? 1 : 0);
		_hashCode = 29 * _hashCode + (int) activo;
		_hashCode = 29 * _hashCode + (activoModified ? 1 : 0);
		if (fechaCreacion != null) {
			_hashCode = 29 * _hashCode + fechaCreacion.hashCode();
		}
		
		_hashCode = 29 * _hashCode + (fechaCreacionModified ? 1 : 0);
		if (usuarioCreacion != null) {
			_hashCode = 29 * _hashCode + usuarioCreacion.hashCode();
		}
		
		_hashCode = 29 * _hashCode + (usuarioCreacionModified ? 1 : 0);
		if (fechaUltimaModificacion != null) {
			_hashCode = 29 * _hashCode + fechaUltimaModificacion.hashCode();
		}
		
		_hashCode = 29 * _hashCode + (fechaUltimaModificacionModified ? 1 : 0);
		if (usuarioUltimaModificacion != null) {
			_hashCode = 29 * _hashCode + usuarioUltimaModificacion.hashCode();
		}
		
		_hashCode = 29 * _hashCode + (usuarioUltimaModificacionModified ? 1 : 0);
		_hashCode = 29 * _hashCode + categoriaIdCategoria;
		_hashCode = 29 * _hashCode + (categoriaIdCategoriaModified ? 1 : 0);
		_hashCode = 29 * _hashCode + catalogoIdCatalogo;
		_hashCode = 29 * _hashCode + (catalogoIdCatalogoModified ? 1 : 0);
		return _hashCode;
	}

	/**
	 * Method 'createPk'
	 * 
	 * @return ProductoPk
	 */
	public ProductoPk createPk()
	{
		return new ProductoPk(idProducto);
	}

	/**
	 * Method 'toString'
	 * 
	 * @return String
	 */
	public String toString()
	{
		StringBuffer ret = new StringBuffer();
		ret.append( "edu.co.sena.onlineshop.integracion.dto.Producto: " );
		ret.append( "idProducto=" + idProducto );
		ret.append( ", nombreProducto=" + nombreProducto );
		ret.append( ", precio=" + precio );
		ret.append( ", imagen=" + imagen );
		ret.append( ", cantidad=" + cantidad );
		ret.append( ", activo=" + activo );
		ret.append( ", fechaCreacion=" + fechaCreacion );
		ret.append( ", usuarioCreacion=" + usuarioCreacion );
		ret.append( ", fechaUltimaModificacion=" + fechaUltimaModificacion );
		ret.append( ", usuarioUltimaModificacion=" + usuarioUltimaModificacion );
		ret.append( ", categoriaIdCategoria=" + categoriaIdCategoria );
		ret.append( ", catalogoIdCatalogo=" + catalogoIdCatalogo );
		return ret.toString();
	}

}
